### ISSUE TITLE
New order indicator badge on the Order tab of vendor dashboard

### ISSUE THREAD

**Issue by J-H-Mojumder** [getdokan/dokan#1221]
**Description**
It would be nice if the **Orders** tab of the vendor dashboard had a notification badge if there is a new order made to the vendor.

**How to reproduce:**
1. Log in as a vendor.
2. Navigate to the vendor dashboard.
3. There is no indicator on the tab if a new order is issued for the vendor.

**Possible Workflow:**

It would be nicer if the Orders tab also had a notification badge while a new order is made like the store support right now. The support tab right now looks like [this screenshot](https://prnt.sc/13th539) when a new store support ticket is issued.

Also, It will be great to have this feature on the **Followers** and **Reviews** tab too though they are in the Dokan Pro version.

**Comment by Tangol** [comment]
This would be an amazing addition and pretty easy to implement too.
Looking forward to it.
Thanks!

**Comment by mrabbani** [comment]
It is addressed in #2223.
