### ISSUE TITLE
Total number of orders when mouseover the customer name

### ISSUE THREAD

**Issue by Tangol** [getdokan/dokan#1246]
We have many cases of repeat customers that frequently place orders and it would be nice that when we mouseover their name, we could see the total number of orders they had for that vendor.
The script should return all orders, regardless of their status (completed, canceled, refunded, failed etc.), as it would also help with tracking bad customers (customers that place tons of fake orders, or customers that request their money back a lot, etc.).

Something like we have on the order `Date`:
![total](https://user-images.githubusercontent.com/3336728/121686021-52b89d80-cac9-11eb-9eff-8a0bb80238f9.png)

Thanks!

**Comment by nurul-umbhiya** [comment]
Invalid

**Comment by nurul-umbhiya** [comment]
Perhaps make a new customer page where vendor's will see that customer lifetime transaction history.

**Comment by Tangol** [comment]
> Perhaps make a new customer page where vendor's will see that customer lifetime transaction history.

Yes, that would be the ideal way to do it, as you can see in an example below.

![customers](https://user-images.githubusercontent.com/3336728/133075258-b1ac0ead-cd8b-416f-a480-d9f22556a30d.png)

However, it's more complex and harder to implement than a simple query that returns the total number of orders, like in my suggestion.
The mouseover feature is super-useful as it gives us the ability to quickly check if the order is from a repeat customer (maybe you want to reward him with a discount, for being a loyal customer).
Either way, it's your call.

Thanks!

**Comment by nurul-umbhiya** [comment]
@Tangol if we had to do it, we will do it in a way so that everyone gets benefited from this feature. Thanks for your suggestion, we are considering this as a new feature.

**Comment by imtiaz-pranto** [comment]
After feasibility study, it seems that it would be better to consider this with customer profile than the order table. We will work on it to make the process easier with further enhancement. Closing this issue and considering it as an enhancement in future.
