### ISSUE TITLE
Ask for product review - vendor

### ISSUE THREAD

**Issue by ProRealCode** [getdokan/dokan#1405]
When a vendor is creating a product, there is no way that the marketplace admin know when it is finished and when it should be reviewed to be published.

Is it possible to add a small button in the product edit page for vendors, for them to ask for a review of the selected product?

With an up growing list of vendors, a lot of products can be added every day and apart from browsing the WooCommerce products lists, it is not possible to know what products are in "pending review". Also, even if a product is in pending review, the page could be not yet finalized by the vendor and there is no way to know that for the marketplace admin.

So there should be a "review tool" to alert admin if a product is "ready for reviewing".

**Comment by nurul-umbhiya** [comment]
> With an up growing list of vendors, a lot of products can be added every day and apart from browsing the WooCommerce products lists, it is not possible to know what products are in "pending review". Also, even if a product is in pending review, the page could be not yet finalized by the vendor and there is no way to know that for the marketplace admin.

With Dokan version 3.8.2, we've introduced the Single Step Product Creation feature as well as the vendor's capabilities to make a product draft while creating or updating a product. If you set **Product Status** to **Pending Review** from Dokan admin settings, the vendor can save a draft product unless they are ready to publish it. If Pending Review was selected after they'll see the Pending Review option to ask for a review.
