### ISSUE TITLE
Add multilingual capability for global 'store' slug URL setting

### ISSUE THREAD

**Issue by lonifasiko** [getdokan/dokan#1573]
Our Dokan-based ecommerce project needs to support two languages, English and Spanish. We've WPML installed and configured, along with WooCommerce Multilingual. 

I've seen you can set in Dokan settings the word that will be part of the slug URL of vendor stores, by default set to 'store'. No problem in using 'store' for English (like this: https://mymarketplace.com/en/**store**/store1/) but I would need to use 'tienda' for Spanish (like this https://mymarketplace.com/es/**tienda**/store1/) users in the slug URL of each vendor store.

As you may suppose, it makes no sense for a Spanish user to see English words in the URL of their navigator, and viceversa. 

Hope you can take this feature request into consideration for future updates. 

Thanks very much in advance. 

Best regards from Spain, 
Miguel.

**Comment by YeasinArafat1998** [comment]
You can subscribe to this issue for further discussion: https://github.com/getdokan/dokan/issues/2081
