### ISSUE TITLE
Withdraw, provide the details on how the final amount was determined

### ISSUE THREAD

**Issue by oliviertassinari** [getdokan/dokan#1588]
**Is your feature request related to a problem? Please describe.**

I'm looking for a way to build an invoice for each vendor with a breakdown of all the items that were sold that once summed lead to the withdrawal amount. 

**Describe the solution you'd like**

Unclear, as simple as a CSV would already help a lot.

**Describe alternatives you've considered**

Currently, we are doing SQL queries with the `posts` table, but it's not always reliable, especially with complex refund and multi-item order cases.

**Comment by nurul-umbhiya** [comment]
@oliviertassinari Can you provide any mockup or design for what you are expecting? Also a details description of you are looking for is highly apprit

**Comment by oliviertassinari** [comment]
I think that it could be an extract of the `wp_dokan_vendor_balance` that corresponds to the withdrawal, or ideally be a compressed view of the orders, per item:

| Description            | Count  | Commission | Total  |
|------------------------|--------|-------|--------|
| Foo - Standard License | 1      | 32.98 | 32.98  |
| Bar - Standard License | 6      | 32.98 | 197.88 |
| Baz - Standard License | 5      | 32.98 | 164.90 |
| Total                  | 395.76 |       |        |
