### ISSUE TITLE
[Dokan API]: The admin is facing restrictions while creating and updating or trying to assign a product to a vendor.

### ISSUE THREAD

**Issue by J-H-Mojumder** [getdokan/dokan#1730]
**Describe the bug**
Few problems regarding the Dokan Product `Create` and `Update` API.
1. The admin can not create a product by changing the `post_author` value of it at the time of creation.
2. The admin is not being able to change the `post_author` value of a product created by him/her to assign the product to a different vendor.
3. The admin is unable to edit the product of any vendor.

**Screenshot:**
https://snipboard.io/f4Njiv.jpg

**To Reproduce**
1. Create a product via API with a `post_author` value of a vendor other than the admin himself/herself.
2. The `post_author` ID will remain the same as the admin's ID.
4. The Same thing happens if the admin tries to modify the `post_author` value of his/her own product.

**Expected behavior**

1. The admin is supposed to be able to create a product with the `post_author` value so that the admin can assign the product to a vendor at the time of creating it.
2. The admin is supposed to be able to edit the `post_author` value of any other vendor.
3. The admin is supposed to be able to edit the product of any other vendor in the marketplace.

**Environment:**
 - Dokan Version: [v3.7.1]
 - Dokan Pro Version: [v3.7.7]
 - WooCommerce Version: [v7.0.0]

**Comment by nurul-umbhiya** [comment]
@J-H-Mojumder This is how the REST API for products has been created five years back. Have you consulted with @Mohaiminulislam1989 bhai for this enhancement?
