### ISSUE TITLE
The min/max feature in Dashboard > Settings is incomplete and misleading

### ISSUE THREAD

**Issue by AmahAjavon** [getdokan/dokan#1732]
Hello,

You have a min/max feature located on the “settings” tab on the vendor dashboard that is a bit misleading. We expected the feature to work as a combined amount count of all products a customer purchases from the same vendor, but it is working per product. Meaning when a min amount is set at $200, each product has to amount to $200 before it can be purchased (for ex: a product cost $40, customer can only buy 5 of it) and this happens for each product a vendor has. 

The functionality needs to also work like this: 

If a vendor sets the minimum amount to $200, when a customer has 1 product from that vendor that costs $20 and another product from the same vendor for $180 in the cart,  it should work at checkout since they add up to $200.  

Hope you can help us fix this issue, or provide us with an add-on feature that can help us add that functionality to the vendor dashboard. 

Best regards,

Amah

**Comment by shashwatahalder01** [comment]
@AmahAjavon, Thank you for your concern regarding the min-max feature. Currently, min-max options are working only for selected products. We are accepting your issue as an enhancement for the min-max module.

**Comment by gindein** [comment]
I am also very interested in the development of this feature. It is an essential requirement for anyone using Dokan as a B2B solution. By purchasing the premium version I thought I could use the min/max option in just this way. Most suppliers require a generic minimum purchase on multiple products in order to ship the goods. I hope you develop this solution soon.

**Comment by YeasinArafat1998** [comment]
The Min and Max module is undergoing restructuring and will be released soon. Once completed, you can expect the module to operate smoothly within your environment. Thank you.
