### ISSUE TITLE
Add an upload button for customers to send documents to vendors

### ISSUE THREAD

**Issue by Advercado** [getdokan/dokan#1756]
**Is your feature request related to a problem? Please describe.**
As the marketplace can be used for many types of service, it would be good to be able to send images/documents to vendors as a customer. There is currently no way to do this in the marketplace, which requires emails outside of the marketplace to achieve this. For example, if you sell business cards as a variable product, in multiple sizes, quantities etc, you can easily create the product in Dokan. However you cant upload/send your design to the vendor. This would be the same for any marketplace that offers customizable products.

**Describe the solution you'd like**
An option to allow attachments with orders if required, if they can be stored with support tickets or get sent directly to the vendor that would be great

**Describe alternatives you've considered**
N/A

**Additional context**
Just a request to facilitate customer uploads for services as mentioned above.

**Comment by nurul-umbhiya** [comment]
This definitely be a great addition to our product. But in the meantime, have you tried [Dokan Product Enquiry](https://wedevs.com/docs/dokan/modules/how-to-install-configure-use-dokan-product-enquiry/) or [Dokan Store Support](https://wedevs.com/docs/dokan/modules/how-to-install-and-use-store-support/) Module?

**Comment by Advercado** [comment]
Hi @nurul-umbhiya,

Thanks for getting back to me.

Yes I use both modules but neither support document sending and it's a vital part of the selling process for our marketplace. 

Can you include this on your roadmap as I'm sure many other customers would benefit from this feature?

Cheers,

Joe

**Comment by Advercado** [comment]
Apologies if you don't work for the company.. somewhat of an assumption : D

**Comment by YeasinArafat1998** [comment]
Hey [Advercado](https://github.com/Advercado), You can utilize the Dokan Product Addon option functionality to meet your needs. [**Here's the link**](https://dokan.co/wordpress/modules/product-addon/) to the module. I'll close this for now, but feel free to reopen it if you have any questions or want to create a support ticket.
