### ISSUE TITLE
Large Category display issues is always in open state 

### ISSUE THREAD

**Issue by KingMilli75** [getdokan/dokan#1909]
Dear,

we use the newest versions of Dokan as is per this post date. Dokan 3.7.19 and Dokan Pro 3.7.22 we use woodmart theme on the site throughout which looks nice with yours now there are 2 major issues! Check out the link provided. 

Issue 1: in large shops read this one has 11k+ articles and about 30 parent and 50+ child categories the default state of the category widget is OPEN state and shows all parent and categories open. Check out he link below.

https://kupoholik.rs/store/shoptogo/section/2206/

We need the default state to be closed and only triggered on click to open the respective category which is clicked. So click event based. On mobile view this looks even more ugly and a impossible scroll. The scroll on desktop is already huge... PLS ASAP help to fix this issue as we are going live in 10 days and this issue need to be fixed by then!! This is ugly and not a good promotion for you guys who can show off this site with large number of products.  Also maybe a smart thing to integrate  this when your already doing to implement the child visibilility via this css snippet as well:

.dokan-store .store-cat-stack-dokan.cat-drop-stack .children{
    padding-left: 5%;
}

Can you provide us the code snippet to rectify this issue so that the category tree is always closed and only on click is being opened, we will insert it via code snippet. Should be easy to be done...

Issue 2: please use the same link, on mobile view on and sometimes on desktop the first and second page of the shop breaks the banners and the pictures are out of alignment it a issue on desktop and mobile.  
![image](https://github.com/weDevsOfficial/dokan/assets/101454545/653e0728-7ae7-4c1e-8741-7877104e6bb9)
![image](https://github.com/weDevsOfficial/dokan/assets/101454545/09bec0cc-c4a0-4e2f-9b97-a7d1cff05054)
![image](https://github.com/weDevsOfficial/dokan/assets/101454545/4f3729f9-9dd9-40a1-94a6-8c1496979f11)
![image](https://github.com/weDevsOfficial/dokan/assets/101454545/368bbcb2-6742-44de-87d5-ae863479da3a)

You can see that the margins on the right side are way off, and there is a huge overflow there. This is screentshot from a p30 pro for example but a lot of android sow this in chrome browser. However when scrolling to the next page it corrects itself this is a issue which has been from the beginning and showing mostly on android devices.  We had this issue on the ihone 12 pro max as well.  This is the correct display...

![image](https://github.com/weDevsOfficial/dokan/assets/101454545/2816b124-7cba-4915-ae7a-2f497b1db5cf)

Cheers,

Dragan

**Comment by nurul-umbhiya** [comment]
@shohag121 Widget will get a fixed height also

**Comment by KingMilli75** [comment]
> @shohag121 Widget will get a fixed height also

when can we expect the fix for the widget?

**Comment by shohag121** [comment]
@nurul-umbhiya Bhai, What would be the ideal max height for the widget list?
