### ISSUE TITLE
I need hooks for add note to withdrawal request

### ISSUE THREAD

**Issue by BeycanDeveloper** [getdokan/dokan#1932]
**Is your feature request related to a problem? Please describe.**
We are developing an integration for Dokan where we handle withdrawal requests. We've completed everything but we want to add an extra feature that might be good for users so we need a hook.

**Describe the solution you'd like**
 "wp-json/dokan/v1/withdraw/1" I tried to add notes by requesting this API, but I think it was rejected due to nonce check. I need to solve this I need to be able to add the transaction id to the note field with any hook.

Then I can show the note here in the list below

![image](https://github.com/weDevsOfficial/dokan/assets/50718965/39363d38-972c-49f1-9d32-b35ab33d3d2b)

**Additional context**
Actually, I have successfully implemented the integration in general. I just think it would be good if the user had the transaction id in the Blockchain. If you make an update that provides this, I can include it in my integration.

**Comment by Aunshon** [comment]
Hello,

I hope this message finds you well. This API "wp-json/dokan/v1/withdraw/1" allows for the modification of certain information, but only the admin has the privilege to do so, while the vendor does not.

To provide you with accurate assistance, we kindly request some additional information. Could you please clarify from which site you are making this request? Additionally, could you let me know if the requester is the admin or the vendor?

**Comment by BeycanDeveloper** [comment]
We are aware of that, sir. The requester is the administrator. The whole process proceeds on the admin side. All we want is to be able to add a note to a withdrawal request with a hook then show that note on the user side.

**Comment by Aunshon** [comment]
Actually the "Withdraw Request Note" is exclusively meant for administrative purposes. It's a space where administrators can jot down any relevant information or notes related to withdrawal requests. Rest assured, these notes are strictly for internal use and are not visible to vendors or anyone else.

While the notes can be updated and edited as needed, they won't be displayed to vendors in any form. The primary intention behind introducing this feature is to offer administrators a way to document specific details or actions related to withdrawals. It ensures that valuable information is recorded for administrative purposes only.

If you have any questions or need further clarification about this, please feel free to reach out. We're here to help!

**Comment by BeycanDeveloper** [comment]
I understand, as I said, my purpose was just to give extra information to the user. If it's not possible, no problem.
