### ISSUE TITLE
Turn “add to cart” button into “Download” button after purchased a Virtual/downloadable products

### ISSUE THREAD

**Issue by TruePixelCreative** [getdokan/dokan#1934]
Dokan missed very important features for the Virtual/downloadable products.

When someone purchased a Virtual/downloadable item, and visit the item page after purchased, he must see something like “download” instead of “add to cart button” again and again, because he already purchased that product or subscribed to a plan to download that products.

Something like add custom text “You own this product” then showing “download” button or swaping add to cart into Download. “something like that”

So, the customers can download the product directly from product page or see notice says “you own this products, click here to go to download page” or something else.. “Similar to Envato Market” https://prnt.sc/XUaY8-ig63B4

----

I founf the solution with Easy digital download + it "All Access extension" So user who purchased All access product can download some products according to categories, tags, or selected products. the only issue with that solution is : did not have a widgets for Elementor to create custom layout page for the downloadable product.

here is a reference for the solution I found: https://prnt.sc/Q3cq-LVGqPzh

**Comment by YeasinArafat1998** [comment]
This feature request is invalid because it goes against the standard WooCommerce functionality, which allows any user to buy a downloadable product twice in any case if it requires shipping.
