### ISSUE TITLE
⚠️⚠️ Vendors see the Stripe fee while admin is paying - in Vendor Dashboard > Orders > Order details > Order items > 

### ISSUE THREAD

**Issue by Sophie-2e** [getdokan/dokan#1954]
**Describe the bug**
In the case when the admin is paying the stripe fees:
In the Vendor Dashboard > Order tabs > Order details > order Note > the seller sees the Stripe fee when he/she is not paying it. 
It is the Admin who is handling the fee, so it does not make sense that the seller sees it (as in the end the stripe fee is included in the commission fee): https://ibb.co/THvZ0Kq

**To Reproduce**
Have Stripe Express as Payment methods.
Have admin pays the stripe commission fee (in woocommerce settings > stripe payment methods > do not select the Take Processing Fees from Sellers option which is not selected by default anyways) 
Log and completed an order and check from the vendor dashboard > Order tabs > Order details > order Note > the seller sees the Stripe fee here

**Expected behavior**
If Admin pays the stripe fee, the seller should not see the stripe fee anywhere, only the admin should see this note and know this information.

**Screenshots**
Screenshots to help explain your problem: https://ibb.co/THvZ0Kq

**Environment (please complete the following information):**
 - Dokan Version: [v3.7.24]
 - Dokan Pro Version: [v3.7.30]
 - WooCommerce Version: [v7.9]
 - Browser [all]
 - Current Theme: [Blocksy - but with all themes]

**Comment by Mohaiminulislam1989** [comment]
@nurul-umbhiya vai we should hide this data from vendor when admin is paying.

**Comment by Sophie-2e** [comment]
Hello Team Dokan, hope you are well, any update on when this will be implemented? :)

**Comment by Sophie-2e** [comment]
Hello @nurul-umbhiya  @aihimel @Mohaiminulislam1989  Any upates on this ? After all last updates, I still see this stripe commission in seller order details, while admin is paying it.

**Comment by Sophie-2e** [comment]
Hello @nurul-umbhiya @aihimel @Mohaiminulislam1989 Any upates on this ? After all latest updates, I still see this stripe commission in seller order details, while admin is paying it.

**Comment by Sophie-2e** [comment]
Hello @nurul-umbhiya @aihimel @Mohaiminulislam1989 Any upates on this?

**Comment by shohag121** [comment]
@tanjiralmamun Bhai,

Would you please let me know if this issue is reported by others or not?

**Comment by tanjiralmamun** [comment]
@shohag121 bhai, did not get reported this issue by others yet.

**Comment by Sophie-2e** [comment]
With the latest update 3.10.2:

- [ ] It still does not work so vendors still see the stripe commission even though the admin is paying it:

![Screenshot 2024-04-09 at 13 25 50](https://github.com/getdokan/dokan/assets/131655229/92f66fcc-21a0-4ddb-bbb3-401c877116cd)

And there is an issue with the translations of the Order Notes that are not accessible at all for vendors that used another language than the default language, reported here: https://github.com/getdokan/dokan-wpml/issues/67

**Comment by Sophie-2e** [comment]
Hello @shohag121 congrats on fixing this issue, you rock! 

I noticed a small improvement which can be done in the future, see it as a feature request: https://github.com/getdokan/dokan/issues/2248 ;-)

Kudos to you for all your hard work this past quarter 🎉👌
