### ISSUE TITLE
Notification bell for Dokan 

### ISSUE THREAD

**Issue by TheGladietor** [getdokan/dokan#1956]
Good evening dear sirs,

I want to make notifications for your plugin with Wp notification bell and I 'm seeing that there isn't any plugin that can do this functionality with your plugin.

Do you know if there is any other plugin with built in notifications inside the multivendor website?

Thank you in advance

**Comment by imtiaz-pranto** [comment]
We will soon bring a new feature enabling built-in notifications in Dokan. Thanks for your feedback.

**Comment by TheGladietor** [comment]
When you say soon... In how many weeks do you believe it will be ready?
