### ISSUE TITLE
Verification Module - Disable automatic Vendor Capability enabled upon successful subscription payment

### ISSUE THREAD

**Issue by Sophie-2e** [getdokan/dokan#1959]
**Is your feature request related to a problem? Please describe.**
Vendor's selling capability is enabled automatically upon successful subscription payment and does not take into consideration whether the vendor has completed the verification process or not (from the verification module).
I see that the seller got automatically enabled once he paid the subscription with Stripe, even if he has not been verified and not been enabled to sell by the admin, while I do have the verification module activated and the option " Enable Selling - enable selling for newly registered vendors" disabled as I need to verify the seller before they can sell on the platform. 
They do need to comply with the verification module process first, and only then they should be enabled to sell. Or if it is automatic with Stripe, then a seller should not be able to buy a pack, until the admin has enabled him to sell on the platform. In any case, for now there is an issue as the vendor can avoid the whole verification process and start to sell directly on the platform without the admin's consent
 
**Describe the solution you'd like**
If we keep the vendors' capabilities enabled automatically upon successful payment (with Stripe Express in my case), then vendors should not be able to select a pack until the admin has enabled them to sell on the platform. Like this, vendors will not pay until they have been verified by the admin, and only once they have been fully verified/enabled by the admin, they can start to pay the platform and so subscribe to a pack.

**Comment by Sophie-2e** [comment]
This is really needed, please 🙌

**Comment by imtiaz-pranto** [comment]
We will try to integrate this into our store verification enhancements soon. Thanks for your feedback.

**Comment by Sophie-2e** [comment]
Also @imtiaz-pranto,  please note that in this scenario, using Stripe Express for subscription, the seller does not receive the email notification "Dokan Vendor Enable" once he has paid the subscription and that his account got automatically enabled. So this email is never sent if we use Stripe Express.

**Comment by Sophie-2e** [comment]
Update since Dokan 3.9:

1. So the main bug is still there (Vendor's selling capability is enabled automatically upon successful subscription payment and does not take into consideration whether the vendor has completed the verification process or not - from the verification module).

2. And update concerning the email sent to the vendor: So now the seller does receive the email notification "Dokan Vendor Enable" once he has paid the subscription but this behaviour is wrong as now he receives the "Dokan Vendor Enable" email template every time they subscribe to a new pack (upgrade or downgrade), while their shops are already enabled, so it does not make sense to receive this email every time stripe processes a subscription payment...

What should happen is that when the verification module is enabled, the "Dokan Vendor Enable" email should only be sent, when the admin enables the vendor.

For the Stripe payment/pack subscriptions, the vendors should automatically receive a specific email which should be an order confirmation with the receipt of the Stripe payment for their subscription = a receipt of their subscription. This will make the life of the admin a lot easier; as for now we should send the invoice manually (but it does not work either anyway as reported here: https://github.com/getdokan/dokan/issues/2012).

So for now we have 0 option to subscription receipts to the vendors, which is not legal.

**Comment by Sophie-2e** [comment]
Hello @imtiaz-pranto , is there any update on this? We really need a way to send invoices to vendors about their subscriptions and block the subcription registration if vendor is not verified yet.

Also noticed that when a vendor cancel his subscription and subscribe to a new one, all subscription will be cancelled on the next billing cycle, resulting with the vendor having 0 subscription anymore, and him to subscribe again...not practical.

**Comment by nurul-umbhiya** [comment]
@imtiaz-pranto Issue 1 and 2 seems logical, we should provide a fix for this, kindly take the necessary steps.
@shashwatahalder01 Bhai can you please check the last comments, AFAIK Stripe Connect does supports Pro-rated billing.

**Comment by Sophie-2e** [comment]
@nurul-umbhiya any update on this?

**Comment by imtiaz-pranto** [comment]
@Sophie-2e We are working on it. Hopefully, it will be available when the enhanced verification module is released.

**Comment by Sophie-2e** [comment]
Happy New Year @imtiaz-pranto, ok good to know but when the enhanced verification module will be released? It is already a year that I hear that Dokan is working on it. I need a date to schedule my own launch which has been constantly delay because of Dokan issues. Thanks for your understanding.

**Comment by Sophie-2e** [comment]
@imtiaz-pranto, when the enhanced verification module will be released?

**Comment by imtiaz-pranto** [comment]
@Sophie-2e Currently I am unable to give a proper date for the release due to complications, but these are in the pipeline and hopefully, we will be able to ship them in this quarter.

**Comment by Sophie-2e** [comment]
Just for info, this is related to the seller subscription too: https://github.com/getdokan/dokan/issues/2196

**Comment by imtiaz-pranto** [comment]
@Sophie-2e , we recently released the reworked vendor verification module, aimed at improving the overall process. However, due to some complications, the specific feature you mentioned was not included in this release. 

I suggest doing some custom coding for this feature if it's really necessary for your marketplace, at least until we release this enhancement. We’re treating it as a priority and hope to release it soon, but we don’t have an exact date yet.

**Comment by Sophie-2e** [comment]
Hello @imtiaz-pranto , yeah just tested it and it is not usable at all. I lost all the previous default Dokan verification settings I had (while everything was translated and working) and on top of that I cannot add any new verification fields...so there is no verification available at all now...already opened a support ticket #64459 with a video showing the errors so you can see yourself 😉

So for now I cannot test it but I am afraid that if there is already a bug in just setting it up, I am not convinced that the rest of the module will work smoothly after when trying to verify the sellers 😅

**Comment by Sophie-2e** [comment]
Hello @imtiaz-pranto I fully tested the new verification module integrated into the wizard and I want to say a big congrats to every Dokan member who has worked on it! 👌💯🎉

You have well implemented the improvements needed and fixed the bugs reported with the old module, as well as streamlined the process a big time for the admin with this new module! I am very happy about it!

There are only a few things to improve but there is a major issue for multilingual marketplaces, which is that it is not translatable. 
I hope to set it up on the live website this month, but for this I need the translation added to it. I believe you are working on the WPML Dokan compatibility plugin which needs lots of major improvements since it has been a long time since it has not been updated (https://github.com/getdokan/dokan-wpml/issues + all the ones I reported via Dokan Customer Support Tickets). 

Can you please tell me if the translations will be added this month of june and when are you going to released this very awaited WPML Dokan plugin update? 🙂

But once again, good job guys! A lot of issues have been tackled 🎉🙌👌💯

**Comment by Sophie-2e** [comment]
Happy Firday @imtiaz-pranto, I love the new verification module (it does miss the translation for Title and Helper texts, hopefully, it will be fixed this month) and the Order Marked as Received module, you really did an amazing job guys! Truly making Dokan greater altogether! 🎉💯🤩
