### ISSUE TITLE
[Refunds] Change order status to refunded automatically after refund is issued

### ISSUE THREAD

**Issue by FLUF-Admin** [getdokan/dokan#1962]
**Describe the bug**
When seller issues refund from single order page, the order status on the right hand side doesn't change automatically. Which is confusing because the refund email depends on that changing and this super confusing for sellers.

**To Reproduce**
On single order page:
- Click request refund
- Fill out numbers
- Confirm refund with modal
- Then nothing happens other than attempt to update table. But order status on the right hand side bar is still what it was

**Expected behavior**
After seller issues a refund (we don't require admin approval on our site) - automatically change order status to refunded.
Else buyer will never receive email that they were refunded!

**Screenshots**

**Environment (please complete the following information):**
 - Dokan Version: Current
 - Dokan Pro Version: Current
 - WooCommerce Version: Current
 - Browser Chrome
 - Current Theme: Reign Theme - latest
 
**Additional context**
- The html template after modal is clicked also doesn't really change or look different to reflect the refund unless the status is explictly changed on the right hand side

**Comment by nurul-umbhiya** [comment]
@Mohaiminulislam1989 This issue seems legit. There is no way for the vendor to know that a refund has been placed unless they tries to make a new refund.

**Comment by Mohaiminulislam1989** [comment]
@nurul-umbhiya vai you can work on this or assign someone. I can't as I don't have permission

**Comment by nurul-umbhiya** [comment]
@Mohaiminulislam1989 bhai this one needs a little bit of analysis. Will talk during office time inshaAllah.

**Comment by Sophie-2e** [comment]
@Mohaiminulislam1989 @nurul-umbhiya not sure if you have worked on it but using Stripe Express Payment, the statut of the order change automatically to Refunded in the Seller dashboard when refund the order from the order details. Just to let you know ;-)

**Comment by Sophie-2e** [comment]
Hello @Mohaiminulislam1989 @nurul-umbhiya @Aunshon, is this something which you plan to implement in a near future, when the refund is made via RMA request in the Seller dashboard?

**Comment by Sophie-2e** [comment]
Happy Friday @shohag121 I saw you closed this GitHub, does that mean it will be released in the next Dokan update this month? 😃

**Comment by shohag121** [comment]
Hello @Sophie-2e,

Yes, It will go on the next release.

**Comment by Sophie-2e** [comment]
Awesome news 😃 🙌 And I guess it is the case for all the ones you just closed 😉 Super dope! Congrats on the dev team for tackling so many bugs, and hopefully WPML issues are going to be resolved soon too 😃

Wishing you an awesome weekend!
