### ISSUE TITLE
No orders showing on Orders page

### ISSUE THREAD

**Issue by mtatlici** [getdokan/dokan#1974]
**Describe the bug**
My vendor click to Orders page there is no order until they click the filter and search their names on customer section and choose their names and apply filter

**To Reproduce**
1. Go to 'orders page '
2. See error

**Expected behavior**
This issue started after updates Dokan and Woocommerce updates

**Environment (please complete the following information):**
 - Dokan Version: 3.8
 - Dokan Pro Version: [e.g. v3.1.2]
 - WooCommerce Version: 8.0.2
 - Browser IE, Firefox, Safari
 - Current Theme: Astra

**Comment by Aunshon** [comment]
Hi @mtatlici ,

To address the issue you're experiencing, please create a support ticket at https://wedevs.com/account/tickets. We'll need to investigate and debug the problem on your website. It's important to note that this issue doesn't exist in our application, so we'll work together to pinpoint and resolve the problem specific to your site.

Thank you for your cooperation, and we'll assist you in resolving this issue promptly.

Best regards
