### ISSUE TITLE
Stripe Express Gateway Processing Fee Invoice Recipient Issue

### ISSUE THREAD

**Issue by daniel-toader** [getdokan/dokan#1988]
When the 'Take Processing Fee from Seller' option is checked, the gateway fee amount is found on the monthly admin invoice.

This fee should appear on the vendor's invoice.

In the EU, this is a deal-breaker.

I'm starting to hear this complaint more and more from the vendors.

I even had a lengthy discussion with my accountant about this.

The payment flow is correct, and there are no issues with it.

Previously, with Stripe Connect, the gateway fee recipient invoice was sent to the vendor if the option was checked."

I contacted Stripe and they provided my with this link, I don't know if this is the right answer:

https://stripe.com/docs/api/invoices/create#create_invoice-transfer_data-amount

**Comment by nurul-umbhiya** [comment]
@daniel-toader We are using Payment Intent API that doesn't require any invoice object (https://stripe.com/docs/api/payment_intents/object). We are using the Separate Charges & Transfer feature of Stripe (https://stripe.com/docs/connect/separate-charges-and-transfers). Can you please ask Stripe Support how to handle the invoice for payment intent? In the meantime, we will try to contact Stripe support from our end. @tanjiralmamun bhai can you please take care of this?

**Comment by daniel-toader** [comment]
@nurul-umbhiya You are right.

@tanjiralmamun according to Stripe: If you don't want to receive a tax invoice that shows the taxes for the Stripe processing fees, you have the option to use direct charges. Using direct charges, the transactions will be processed directly to the Express account, not from your platform. If this is something you'd like to explore:  (https://stripe.com/docs/connect/direct-charges)

If it's hard to achieve, and nobody else needs this, I understand. Dokan Stripe Express is already a wonderful and reliable tool.

We may find a workaround with our accountant; probably, we will need to break down that fee one by one and send it monthly to each vendor
