### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by paablos** [getdokan/dokan#1995]
### Bug Description

Hey everyone, fantastic job!!
I´m new to GitHub so apologies upfront for whatever has been done wrongly on this "Issue" :)

I downloaded and uploaded the files to my server, but got this fatal error:

"Fatal error: Cannot declare class WeDevs_Dokan, because the name is already in use in /home/public_html/wp-content/plugins/dokan-develop/dokan.php on line 58"

What am I doing wrong please???

### Expected Behaviour

Install and active dokan pro,

### Actual Behaviour

Fatal error wich unables installation.

### Environment (please complete the following information)

```shell
1. Dokan Version: v3.8.1
2. Dokan Pro Version: v3.8.1
3. WooCommerce Version: v8.1.0
4. Browser mozilla
5. Current Theme: Woostify
```

**Comment by shohag121** [comment]
Hi @paablos,

As developed versions are not intended for production uses and need many scripts to run correctly, we suggest that you use the **Stable Production** version from [WordPress Org](https://wordpress.org/plugins/dokan-lite/) by visiting the URL below.

https://wordpress.org/plugins/dokan-lite/

Thank You.

**Comment by paablos** [comment]
Hey @shohag121 , thanks for taking the time for commenting.
Thought it was ok for production.
Thanks again, and have a nice day.
