### ISSUE TITLE
Open Graph Social Images Unused

### ISSUE THREAD

**Issue by fisher2470** [getdokan/dokan#1999]
### Bug Description

There is a tab for Social Images in the Store SEO tab, but these images are not utilized in any of the shop template files to actually replace the open graph images being used. 

### Expected Behaviour

I would expect the Store SEO fields to override the default open graph images on stores where the seller has filled out these fields. 

### Actual Behaviour

Instead the main default open graph image is the one loaded every time. 

### Environment (please complete the following information)

```shell
1. Dokan Version: [e.g. v3.1.2]
2. Dokan Pro Version: [e.g. v3.1.2]
3. WooCommerce Version: [e.g. v4.9.2]
4. Browser [e.g. chrome, safari]
5. Current Theme: [e.g. Store Front]
```

**Comment by Aunshon** [comment]
Hi @fisher2470,

We've thoroughly investigated the issue you're facing, but it appears to be specific to your setup. We recommend taking the following steps to resolve it:

1. **Update Dokan**: Please make sure you have the latest versions of both Dokan Lite and Dokan Pro installed on your website. Outdated plugins can sometimes cause compatibility issues.

2. **Contact Support**: If the issue persists after updating, we encourage you to reach out to our support team at https://wedevs.com/account/tickets. Provide them with your website's credentials and screenshots showcasing the problem. We will assist you in resolving this unique issue.

Thank you for your understanding, and we're here to support you in resolving this matter.
