### ISSUE TITLE
Vendor Dashboard > Orders > Order Details - Show empty column no info + Issue Discount Data field + Font Field Quantity Discount 

### ISSUE THREAD

**Issue by Sophie-2e** [getdokan/dokan#2008]
### Bug Description

When we activate the Dokan Pro Plugin:
- [x] 1. there is an empty column which is added to the Order details in the vendor dashboard. According to your support team, this column is supposed to handle the original and discounted price: https://ibb.co/LhRRhhP
- [x] 2. However even if there is a discount for the order, the discount is not taken into consideration so the seller sees 0,00 euro and we still have this empty column: https://ibb.co/LhRRhhP
- [x] 3. The quantity discount field title is not aligned with the other field: https://ibb.co/LhRRhhP

### Step To Reproduce

1. Go to 'Vendor Dashboard'
2. Click on 'Order > Specific Order'
3. Scroll down to 'Order Details'
4. See error: https://ibb.co/LhRRhhP

### Expected Behaviour

1. Don't have the empty column
2. See the right discount amount
3. Have the same title font the "Quantity Discount" than the other fields (discount, shipping, order total...)

### Actual Behaviour

https://share.vidyard.com/watch/7SoDyAzo1gceXBhdS5stNv?

### Additional Information

Video proving it comes from Dokan Pro plugin only. In this video all plugins are deactivated and we have the Elementor theme with no customisation (same results with whatever the theme you take anyways), you see that as soon as we activate Dokan Pro Plugin, it is bugging: https://share.vidyard.com/watch/7SoDyAzo1gceXBhdS5stNv?

### Environment (please complete the following information)

```shell
1. Dokan Version: [v3.8.2]
2. Dokan Pro Version: [v3.8.3]
3. WooCommerce Version: [v8.1.1]
4. Browser [e.g. all]
5. Current Theme: [e.g. Blocksy and Elementor = same problems]
```

**Comment by imtiaz-pranto** [comment]
We have already listed this issue and are working on it to give a cleaner look for order details, which includes even more UI enhancements for our users. Thanks for the feedback.

**Comment by Sophie-2e** [comment]
Yes I know, I did report this bug to your team 3 months ago via your Customer Support platform. But it is still not fixed so at least now I can follow what is going on with it ;-) Thanks

**Comment by Sophie-2e** [comment]
Hello @Aunshon and @imtiaz-pranto , I see this is still not fixed in Dokan 3.9.1 and Pro 3.9.2. When will it be?

**Comment by nurul-umbhiya** [comment]
@Sophie-2e A PR has been given, though we need to implement migration for old data. Hopefully, we will be able to ship this feature on Nov 25th.

**Comment by nurul-umbhiya** [comment]
@Aunshon Bhai kindly add this feature to your priority list.

**Comment by Aunshon** [comment]
![Image](https://github.com/getdokan/dokan/assets/32583103/87af570a-1c1a-49a3-9701-048c86ac164a)

Number 1 issue's fix has been given into the PR
