### ISSUE TITLE
Order Delivery Date Widget Bugs

### ISSUE THREAD

**Issue by Sophie-2e** [getdokan/dokan#2011]
### Bug Description

About this order delivery date module:  https://dokan.co/docs/wordpress/modules/dokan-delivery-time/
I have reported 2 and 3 to your customer support team already but bugs are still there after a few updates.

1. It does not work at all if the admin try to change the date: there is no button on this widget in the admin side and if we click on "Update Button" of "order action", it still does not work, the date does not change: https://ibb.co/fG4btXj

2. Email sent to customer "Dokan Vendor Update Order Delivery Time" template: the tracking code is not working, not clickable, no link: https://ibb.co/YkWp3My

3. "Shipping Status Notification for Customer" template -  {title} placeholder not working in the email subject and email content: https://ibb.co/kXr5npb
https://ibb.co/XpRWZsb

### Step To Reproduce

Cf pictures

### Expected Behaviour

cf bug report

### Actual Behaviour

Order Delivery Date function works when admin use it,  tracking code url link should redirect user to right url and {title} placeholder should display the title.

### Environment (please complete the following information)

```shell
1. Dokan Version: latest
2. Dokan Pro Version: latest
3. WooCommerce Version: latest
4. Browser all
5. Current Theme: Blocksy/Elementor does not matter, same results
```

**Comment by Sophie-2e** [comment]
Update after updating Dokan to 3.9:

STILL NOT WORKING 1. It does not work at all if the admin tries to change the date: there is no button on this widget in the admin side and if we click on the "Update" Button of "order action", it still does not work, the date does not change: https://ibb.co/fG4btXj

FIXED NOW 2. Email sent to customer "Dokan Vendor Update Order Delivery Time" template: the tracking code is not working, not clickable, no link: https://ibb.co/YkWp3My

STILL NOT WORKING 3. "Shipping Status Notification for Customer" template - {title} placeholder not working in the email subject and email content: https://ibb.co/kXr5npb
https://ibb.co/XpRWZsb

NEW BUG - 4. ON SHIPPING MODULE - IN VENDOR DASHBOARD > ORDER DETAILS: CHANGE SHIPPING STATUS TO ANOTHER - Not working at all. It seems that once we have added a first shipping status, we cannot modify it another time so, nothing happens when we click another time on "Update" button, so for now, vendors can say they have shipped the order but cannot change the status afterwards to say it has been delivered or cancelled: https://ibb.co/zXZT92Q

NEW BUG - 5. ON SHIPPING MODULE - IN CUSTOMER DASHBOARD > ORDER TAB: Even when the order has been shipped, and has the status "On the way", it is still shown as "not shipped": https://ibb.co/fqVdhyb

**Comment by Sophie-2e** [comment]
Hello @nurul-umbhiya, I just remade a test to check everything again after updating Woocommerce and here are my findings:

1. SOLVED: Now the admin CAN change the delivery date too so previously it might have been related to Woo.

NEW - 2.  However, when the admin changes the date now, the customer and vendors do NOT receive the "Dokan Admin Update Order Delivery Time" email. It is not being sent at all and this is related to Dokan. 

3. SOLVED: "Shipping Status Notification for Customer" template - {title} placeholder - the description for placeholders has been changed explaining that we cannot use this placeholder now in this email. 

4. ON SHIPMENTS MODULE - IN VENDOR DASHBOARD > ORDER DETAILS: CHANGE SHIPPING STATUS TO ANOTHER - Not working at all. It seems that once we have added a first shipping status, we cannot modify it another time so, nothing happens when we click another time on "Update" button, so for now, vendors can say they have shipped the order but cannot change the status afterwards to say it has been delivered or cancelled: https://ibb.co/zXZT92Q

5. ON SHIPMENTS MODULE - IN CUSTOMER DASHBOARD > ORDER TAB: Even when the order has been shipped, and has the status "On the way", it is still shown as "not shipped" instead of "not delivered": https://ibb.co/fqVdhyb. After investigating the matter with Sazzat Hossain, I understood that it is in fact Dokan who does not use the correct English word. **It should be written "not delivered/delivered"** instead of "not shipped/shipped". Because "not shipped", means that the vendor did not send it yet, meaning that the order has not left the seller's location, while what Dokan means with "Not shipped", is that the customer has not been delivered. This is very confusing for customers who are going to contact the admin/vendors wondering why their order is shown as "not shipped" when they did receive an email saying the order is on the way...this is contradictory and such a waste of time for the admin/sellers to answer all these customer support emails just because the word is not correct in the customer dashboard.

**Comment by Sophie-2e** [comment]
@aihimel and @nurul-umbhiya Update after testing on Dokan 3.9.1 and Pro 3.9.2:

1. ON SHIPMENTS MODULE - IN VENDOR DASHBOARD > ORDER DETAILS: CHANGE SHIPPING STATUS TO ANOTHER - Not working at all. It seems that once we have added a first shipping status, we cannot modify it another time so, nothing happens when we click another time on "Update" button, so for now, vendors can say they have shipped the order but cannot change the status afterwards to say it has been delivered or cancelled: https://ibb.co/zXZT92Q

2. ON SHIPMENTS MODULE - IN CUSTOMER DASHBOARD > ORDER TAB: Even when the order has been shipped, and has the status "On the way", it is still shown as "not shipped" instead of "not delivered": https://ibb.co/fqVdhyb. After investigating the matter with Sazzat Hossain, I understood that it is in fact Dokan who does not use the correct English word. It should be written "not delivered/delivered" instead of "not shipped/shipped". Because "not shipped", means that the vendor did not send it yet, meaning that the order has not left the seller's location, while what Dokan means with "Not shipped", is that the customer has not been delivered. This is very confusing for customers who are going to contact the admin/vendors wondering why their order is shown as "not shipped" when they did receive an email saying the order is on the way...this is contradictory and such a waste of time for the admin/sellers to answer all these customer support emails just because the word is not correct in the customer dashboard.

3. Admin can change the delivery date now but vendors and customers do not receive any email updates about it.

**Comment by nurul-umbhiya** [comment]
@Sophie-2e A PR was given for issue no 1 two weeks ago, hopefully, you'll get the update on the next release. 
We couldn't reproduce issue 3, @rajankarmakar can you please check that issue no 3 exists on the development branch?
@Mohaiminulislam1989 @imtiaz-pranto Can you please check issue no 2? It seems valid to me.

**Comment by shashwatahalder01** [comment]
@nurul-umbhiya , issue no 3 doesn't reproduce on development branch [screenshot] (https://prnt.sc/GYPQepPtm-N2)

**Comment by Sophie-2e** [comment]
@shashwatahalder01 Issue 1. ON SHIPMENTS MODULE - IN VENDOR DASHBOARD > ORDER DETAILS: CAN'T CHANGE SHIPPING STATUS TO ANOTHER - Ok when will it be released then?

Issue 2. ON SHIPMENTS MODULE - IN CUSTOMER DASHBOARD > ORDER TAB > shipped / not shipped labels: Very needed as for now it is so confusing for customers and will create too many customer support tickets just because there is an English mistake 😅

@shashwatahalder01, @nurul-umbhiya   Issue 3 is there even when 0 plugin activated and a basic default theme activated so you should be able to reproduce it. Here is this video as proof and showing how to reproduce the error. You will see that 0 emails are sent when admin changes the delivery date: https://share.vidyard.com/watch/WSV8gR7cZWYSTkHtc33xjq?

Waiting for your news

**Comment by imtiaz-pranto** [comment]
@aihimel bhai, In the Shipments module on the customer dashboard's order tab, please update the status text:
- Change "Not Shipped" to "Not Delivered"
- Change "Shipped" to "Delivered"

@Sophie-2e for issue 3, it seems like a site-specific issue, reach out to our support team for further assistance.

**Comment by Sophie-2e** [comment]
@imtiaz-pranto Awesome for 1 and 2! I will keep an eye on the next update. Thank you.

For 3 indeed, after a thorough investigation, I found out that it is YaYMail for Dokan plugin which is causing the issue so already in touch with their dev team to fix it ;-)

**Comment by Sophie-2e** [comment]
@imtiaz-pranto @nurul-umbhiya Oh and there this issue too:

4. ON SHIPMENTS MODULE > Dokan Admin Update Order Delivery Time email template: as only one email is sent to both customers and vendors, the vendors have access to the customer's email address and the customer can also see the vendor's email address while we have the option to hide this information enabled in Dokan Admin settings. The customer and vendor should only be able to see their own email, but not the one of the other. So either hide the other email address when it is sent so the receiver only sees his own address, or have two different templates sent (one for the customer, one for the vendor). 

Waiting for your news on this one.

**Comment by nurul-umbhiya** [comment]
@Sophie-2e After the next release of Dokan Lite and Dokan Pro, kindly check if all the issues mentioned here have been fixed. If some issues are left behind, kindly crate a new GitHub issue mentioning the mission ones.

**Comment by Sophie-2e** [comment]
@nurul-umbhiya Ok when the next update will be released?

**Comment by nurul-umbhiya** [comment]
@Sophie-2e Possibly Today, if not Next Monday.

**Comment by Sophie-2e** [comment]
@nurul-umbhiya Awesome, glad to hear, thank you very much and good luck then :)
