### ISSUE TITLE
Can't Send The Email Invoice on Dokan Subscription Pack

### ISSUE THREAD

**Issue by Sophie-2e** [getdokan/dokan#2012]
### Bug Description

in admin > woo > orders > order detail: Order Actions > Email Invoice / order details to customer > functionality not working only on dokan subscription pack and redirecting to this error page: https://ibb.co/2v88B9N

With error log: 

[error] 2526#2526: *705 FastCGI sent in stderr: "PHP message: PHP Fatal error: Uncaught Exception: Order status is missing. in /www/website/public/wp-content/plugins/woocommerce/includes/admin/meta-boxes/class-wc-meta-box-order-data.php:600
Stack trace:
#0 /www/website/public/wp-includes/class-wp-hook.php(312): WC_Meta_Box_Order_Data::save(25195)
#1 /www/website/public/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters(NULL, Array)
#2 /www/website/public/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#3 /www/website/public/wp-content/plugins/woocommerce/src/Internal/Admin/Orders/Edit.php(234): do_action('woocommerce_pro...', 25195, Object(Automattic\WooCommerce\Admin\Overrides\Order))
#4 /www/website/public/wp-content/plugins/woocommerce/src/Internal/Admin/Orders/Edit.php(147): Automattic\WooCommerce\Internal\Admin\Orders\Edit->handle_order_update()
#5 /www/website/public/wp-content/plugins/woocommerce/src/Internal/Admin/Orders/PageController.php(350): Automattic\WooCommerce\Internal\Admin\Orders\Edit->setup(Object" while reading response header from upstream, client: 2001:1c00:1531:7200:305d:230d:4531:4ff6, server: server-address, request: "POST /wp-admin/admin.php?page=wc-orders&action=edit&id=25195 HTTP/2.0", upstream: "fastcgi://unix:/var/run/php8.2-fpm-servername.sock:", host: "website-address:47745", referrer: "https://websiteurl/wp-admin/admin.php?page=wc-orders&action=edit&id=25195"

### Step To Reproduce

in admin > woo > orders > order detail: Order Actions > Email Invoice / order details to customer > functionality not working 

### Expected Behaviour

be able to send the customer(seller) invoice manually on dokan subscription order.

### Actual Behaviour

cf Bug Description

### Environment (please complete the following information)

```shell
1. Dokan Version: latest
2. Dokan Pro Version: latest
3. WooCommerce Version: latest
4. Browser all
5. Current Theme: [Store Front/elementor/blocksy]
```

**Comment by Sophie-2e** [comment]
and actually, we should just have an automatic Email Template such as "Vendor Susbcription Invoice" which should be sent automatically every time the renewal is happening/everytime the subscription is paid. Like you have fromm any subription based company like Netflix, Amazon Sellers, Spotify, Apple etc...

**Comment by Sophie-2e** [comment]
Updated to Dokan 3.9 and bug still here, send manual invoice still not possible : 

For the Stripe payment/pack subscriptions, the vendors should automatically receive a specific email which should be an order confirmation with the receipt of the Stripe payment for their subscription = a receipt of their subscription. This will make the life of the admin a lot easier; as for now we should send the invoice manually (but it does not work either anyway as reported here above).

So for now we have 0 option to subscription receipts to the vendors, which is not legal.

**Comment by Sophie-2e** [comment]
Hello, after Dokan 3.9.1 and Pro 3.9.2. This error is still there and I noticed that none of the actions work as they all create a fatal error (same for resend new order notification + regenerate download permission). A solution is absolutely needed as we need to send invoices to our vendors to be compliant with European laws. Waiting for your news. Do you have a temporary solution?

**Comment by nurul-umbhiya** [comment]
@Sophie-2e I couldn't reproduce this issue on my end. Need to this this on your staging site. I tried to log in, but the login details aren't working anymore. Can you please contact the support team and send new login details?
Kindly use `getdokan/client-issue/issues/34` as a reference.

**Comment by Sophie-2e** [comment]
@nurul-umbhiya weird because I have the issue even with no plugins activated and a basic theme. Anyways. just created the dokan ticket again [#26718]

Waiting for your news

**Comment by Sophie-2e** [comment]
@nurul-umbhiya issue is still here even after last update. This is so important to be legally compliant. When will it be fixed?

**Comment by Sophie-2e** [comment]
Hello @nurul-umbhiya, so it does come from Dokan as explained previously, and @YeasinArafat1998 provide me with the solution to fix it. It needs to plugin fix in Dokan Pro in: dokan-pro/modules/subscription/includes/admin/admin.php.

Replace line 231 with:

if ( ! empty( $subscription_screen_id ) ) {
            remove_meta_box( 'woocommerce-order-data', $subscription_screen_id, 'normal' );
}

Please make sure to change it next updates so Dokan users do not have to update the plugin manually to fix this issue after each update. Thanks, and thanks to @YeasinArafat1998 for finding the roots of the cause, on the solution.

**Comment by Sophie-2e** [comment]
Hello @nurul-umbhiya , just learned from @YeasinArafat1998 that you are the one who found the solution, just want to say a big thank you to you for finding the roots of the issue and the solution, you rock! This was a major issue in the use of Dokan to be legally compliant! It is still a manual solution to send the invoices to vendors, but at least admin has a temporary solution until those features are launched: https://github.com/getdokan/dokan/issues/1959 :)

Thanks again!

**Comment by Sophie-2e** [comment]
Hello @nurul-umbhiya will the fix you provided be added to the next Dokan release? And if yes, which version? Thanks for your help.

**Comment by nurul-umbhiya** [comment]
@Sophie-2e It will be fixed on next version of the Dokan Pro.

**Comment by Sophie-2e** [comment]
You rock @nurul-umbhiya ! Thank you!
