### ISSUE TITLE
CUSTOMER SUPPORT functionalities - Bugs

### ISSUE THREAD

**Issue by Sophie-2e** [getdokan/dokan#2013]
### Bug Description

1. When customer creates a new ticket, nobody receives an email notification while vendor and admin should receive an email (Dokan New Support Ticket email / Dokan New Support Ticket For Admin email): https://ibb.co/Kr54W01.

2. Old bug reported 3 months ago: Can't enable email for admin and seems deactivated. 
2.1: The one sent to admin for a new ticket does not work at all anymore (while it used to work fine): https://ibb.co/G58DC00, 
2.2: and the one sent to the admin when there is a reply works but is still shown inactive: https://ibb.co/Kr54W01

3. Reply on a support ticket: so as explain above: the one sent to the admin when there is a reply works but is still shown inactive: https://ibb.co/Kr54W01
3.1 Seller does not receive the email "Dokan Reply To Store Support Ticket"
3.2 and customer has no idea as the email [Dokan Reply to User Support Ticket] is not sent and the admin cannot replies either so not sure if the customer receives the [Dokan Reply To Admin Support Ticket From Vendor & Customer]...

### Step To Reproduce

https://dokan.co/docs/wordpress/modules/how-to-install-and-use-store-support/

### Expected Behaviour

cf bug report

### Actual Behaviour

cf bug report

### Environment (please complete the following information)

```shell
1. Dokan Version: latest
2. Dokan Pro Version: latest
3. WooCommerce Version: latest
4. Browser all
5. Current Theme:  Store Front / Blocksy / Elementor
```

**Comment by nurul-umbhiya** [comment]
@Sophie-2e Can you please create a support ticket referencing this issue number and provide us a staging site for testing purposes? We will look into ins ASAp.

**Comment by Sophie-2e** [comment]
Hello @nurul-umbhiya, yes I already opened a customer ticket at the same time as this GitHub issue. Here is the reference of it where you can find credentials to a staging website: 
Ticket [#23348] CUSTOMER SUPPORT MODULE COMPLETLY DOWN WITH DOKAN 3.9!

Waiting for your news
