### ISSUE TITLE
Changing the Twitter icon from Twitter to X in the entire plugin.

### ISSUE THREAD

**Issue by shashwatahalder01** [getdokan/dokan#2026]
### Bug Description

Changing the Twitter icon from Twitter to X in the entire plugin.

Screenshots:
Social Profile: https://snipboard.io/no3JUz.jpg
Store Share: https://snipboard.io/1sfFov.jpg
Social Login: https://snipboard.io/5OIlcs.jpg
Seller Verification: https://snipboard.io/6QJA7r.jpg

**Comment by Sophie-2e** [comment]
@YeasinArafat1998 , @nurul-umbhiya Any update on the release date?

**Comment by nurul-umbhiya** [comment]
Fixed with the latest version of Dokan

**Comment by Sophie-2e** [comment]
Congrats and thanks @shashwatahalder01 , @Aunshon and @nurul-umbhiya  🎉 
 
There is just an issue with the Dokan Elementor Store Social Profile widget where it misses the X icon resulting in the social media icon not being rendered in front end on Vendor Store Page built with Elementor, even if vendors have added a X/Twitter social media profile.

GitHub issue open here, please assign someone: https://github.com/getdokan/dokan/issues/2208
