### ISSUE TITLE
BUG - Vendor Analytics not working in Vendor Report for "Overview" and "Sales By Day" tabs since Dokan v3.9

### ISSUE THREAD

**Issue by Sophie-2e** [getdokan/dokan#2045]
### Bug Description

The analytics reports ("Overview" and "Sales By Day") are not working in the vendor dashboard > Report tab.

Even if they made sales, and played with the filters, they do not see any sale analytics.

### Step To Reproduce

Vendord Dashboard > Check Reports for "Overview" and "Sales By Day" tabs > all data empty

### Expected Behaviour

To have the analytics.

### Actual Behaviour

No analytics are shown even if orders have been completed: 
https://ibb.co/kKPFpPZ
https://ibb.co/RNsXZ7m
https://ibb.co/qrdrH02
https://ibb.co/3kmVyNh

### Environment (please complete the following information)

```shell
1. Dokan Version: [3.9]
2. Dokan Pro Version: [3.9]
3. WooCommerce Version: [8.1.1]
4. Browser [all]
5. Current Theme: [Store Front, elementor, blocksy = all themes]
```

**Comment by nurul-umbhiya** [comment]
@Sophie-2e Kindly create a support ticket for this. We are not able to reproduce this on our end.

**Comment by nurul-umbhiya** [comment]
@Sophie-2e I just checked your test site and found out that the HPOS feature is enabled on your site. If the HPOS feature is enabled, you'll also need to enable the Sync feature for now. Instruction is added below image:
<img width="1109" alt="Screenshot 2023-10-12 at 3 42 42 PM" src="https://github.com/getdokan/dokan/assets/10240343/e61a0fe2-e488-4411-859f-4997b4924eef">
You'll be glad to know that, we are working on the report feature for the vendor dashboard and the report page will be redesigned from the ground up with lots of new features and enhancements.

**Comment by Sophie-2e** [comment]
Hello @nurul-umbhiya ! Thank you so much! Indeed enabling this option fixed the issue 🙌

I am glad to hear that you are working on it because it is indeed not readable as it is for now, too much info on one graph - and I saw lots of Dokan users making comments about this in the Dokan Facebook group. 

Will this functionality also be part of the redesign: https://app.loopedin.io/dokan?card=64363ea10853050028ed560e ? 😃

Hopefully, you are also thinking about the admin report which also required some improvements: https://github.com/getdokan/dokan/issues/1952 😉
