### ISSUE TITLE
BUG - CUSTOMER MIGRATION TO SELLER FORM - PHP Warning: Undefined variable

### ISSUE THREAD

**Issue by Sophie-2e** [getdokan/dokan#2046]
### Bug Description

If you add the shortcode [dokan-customer-migration] for the customer migration form on a page, and then visit the page, you get errors in the error log because various variables are not defined:

2023/10/09 18:14:38 [error] 5536#5536: *709 FastCGI sent in stderr: "PHP message: PHP Warning: Undefined variable $first_name in /www/your_name/public/wp-content/plugins/dokan-lite/templates/account/update-customer-to-vendor.php on line 24; PHP message: PHP Warning: Undefined variable $last_name in /www/your_name/public/wp-content/plugins/dokan-lite/templates/account/update-customer-to-vendor.php on line 28; PHP message: PHP Warning: Undefined variable $shop_name in /www/your_name/public/wp-content/plugins/dokan-lite/templates/account/update-customer-to-vendor.php on line 34; PHP message: PHP Warning: Undefined variable $shop_url in /www/your_name/public/wp-content/plugins/dokan-lite/templates/account/update-customer-to-vendor.php on line 40; PHP message: PHP Warning: Undefined variable $phone in /www/your_name/public/wp-content/plugins/dokan-lite/templates/account/update-customer-to-vendor.php on line 46; PHP message: PHP Warning: Undefined variable $show_toc in /www/your_name/public/wp-content/plugins/dokan-lite/templates/account/update-customer-to-vendor.php on line 57; PHP message: PHP Warning: Undefined variable $user_id in /www/your_name/public/wp-content/plugins/dokan-lite/templates/account/update-customer-to-vendor.php on line 74" while reading upstream, client: 2001:1c00:1531:7200:3132:b009:61b9:c2e5, server: website_url, request: "GET /customer-migration-to-seller/ HTTP/2.0", upstream: "fastcgi://unix:/var/run/php8.2-fpm-your_name.sock:", host: "website_url:47745"

### Step To Reproduce

If you add the shortcode [dokan-customer-migration] for the customer migration form on a page, and then visit the page, you get errors in the error log because various variables are not defined:

2023/10/09 18:14:38 [error] 5536#5536: *709 FastCGI sent in stderr: "PHP message: PHP Warning: Undefined variable $first_name in /www/your_name/public/wp-content/plugins/dokan-lite/templates/account/update-customer-to-vendor.php on line 24; PHP message: PHP Warning: Undefined variable $last_name in /www/your_name/public/wp-content/plugins/dokan-lite/templates/account/update-customer-to-vendor.php on line 28; PHP message: PHP Warning: Undefined variable $shop_name in /www/your_name/public/wp-content/plugins/dokan-lite/templates/account/update-customer-to-vendor.php on line 34; PHP message: PHP Warning: Undefined variable $shop_url in /www/your_name/public/wp-content/plugins/dokan-lite/templates/account/update-customer-to-vendor.php on line 40; PHP message: PHP Warning: Undefined variable $phone in /www/your_name/public/wp-content/plugins/dokan-lite/templates/account/update-customer-to-vendor.php on line 46; PHP message: PHP Warning: Undefined variable $show_toc in /www/your_name/public/wp-content/plugins/dokan-lite/templates/account/update-customer-to-vendor.php on line 57; PHP message: PHP Warning: Undefined variable $user_id in /www/your_name/public/wp-content/plugins/dokan-lite/templates/account/update-customer-to-vendor.php on line 74" while reading upstream, client: 2001:1c00:1531:7200:3132:b009:61b9:c2e5, server: website_url, request: "GET /customer-migration-to-seller/ HTTP/2.0", upstream: "fastcgi://unix:/var/run/php8.2-fpm-your_name.sock:", host: "website_url:47745"

### Expected Behaviour

Don't have issue -  define variable in shortcode

### Actual Behaviour

If you add the shortcode [dokan-customer-migration] for the customer migration form on a page, and then visit the page, you get errors in the error log because various variables are not defined:

2023/10/09 18:14:38 [error] 5536#5536: *709 FastCGI sent in stderr: "PHP message: PHP Warning: Undefined variable $first_name in /www/your_name/public/wp-content/plugins/dokan-lite/templates/account/update-customer-to-vendor.php on line 24; PHP message: PHP Warning: Undefined variable $last_name in /www/your_name/public/wp-content/plugins/dokan-lite/templates/account/update-customer-to-vendor.php on line 28; PHP message: PHP Warning: Undefined variable $shop_name in /www/your_name/public/wp-content/plugins/dokan-lite/templates/account/update-customer-to-vendor.php on line 34; PHP message: PHP Warning: Undefined variable $shop_url in /www/your_name/public/wp-content/plugins/dokan-lite/templates/account/update-customer-to-vendor.php on line 40; PHP message: PHP Warning: Undefined variable $phone in /www/your_name/public/wp-content/plugins/dokan-lite/templates/account/update-customer-to-vendor.php on line 46; PHP message: PHP Warning: Undefined variable $show_toc in /www/your_name/public/wp-content/plugins/dokan-lite/templates/account/update-customer-to-vendor.php on line 57; PHP message: PHP Warning: Undefined variable $user_id in /www/your_name/public/wp-content/plugins/dokan-lite/templates/account/update-customer-to-vendor.php on line 74" while reading upstream, client: 2001:1c00:1531:7200:3132:b009:61b9:c2e5, server: website_url, request: "GET /customer-migration-to-seller/ HTTP/2.0", upstream: "fastcgi://unix:/var/run/php8.2-fpm-your_name.sock:", host: "website_url:47745"

### Environment (please complete the following information)

```shell
1. Dokan Version: [3.9]
2. Dokan Pro Version: [3.9]
3. WooCommerce Version: [8.1.1]
4. Browser [all]
5. Current Theme: [Store Front, blocksy, hello elementor = all themes]
```

**Comment by nurul-umbhiya** [comment]
@Sophie-2e Fixed has been provided on Dokan Pro, you'll get the fix on the next version of Dokan Pro. If you need an urgent fix, please create a support ticket. They'll help you implement the fix on your site. 
Reference commit: https://github.com/getdokan/dokan-pro/commit/e07f4481266fdba686f26eae3d60122d272509f8

**Comment by Sophie-2e** [comment]
Hello @nurul-umbhiya, ok thanks for the follow up, will it be released in Dokan 3.9.1?

**Comment by nurul-umbhiya** [comment]
@Sophie-2e Yes, a possible release date is 20th October.

**Comment by Sophie-2e** [comment]
Thank you very much @nurul-umbhiya for fixing it 💯
