### ISSUE TITLE
WORDPRESS NEW COMMENT / NEW REVIEW NOTIFICATION: Send to vendor now with customer details

### ISSUE THREAD

**Issue by Sophie-2e** [getdokan/dokan#2048]
### Bug Description

Previously the email notification sent by worpress when a comment is adding on the blog or a review on a product, was only sent to the admin. And it was very fine like that as there is admin url link in this email notification including consumer details.

But since Dokan 7.9, this notification is not sent to the admin at all, and instead, it is sent to the vendor...with all admin url + customers email while we hide this info from the sellers, and it also show the actions link like trash it or spam it while the admin does not enable the vendor to manage the review: https://ibb.co/vmk76fR

This is a very bad idea.

### Step To Reproduce

1.From a customer profile, add a review on a product
2. check emails sent - admin get nothing while vendor got email with admin urls and customer's email

### Expected Behaviour

The default wordpress notif should only be sent to the admin while Dokan should create an email template dedicated to this matter and only sent to the vendor -> create a "Dokan Vendor New Product Review" email template.

Admin should be able to change the subject and heading, like we can do for other Dokan email templates in Woocommerce > Settings > Email

In this template dedicated to vendors, we should not see the customer contact info, we should only see:
1. the name of the customer (first name and last name)
2. the comment/review
3. the star rating
4. the url link to the comment on the product page
5. Don't see any action links like trash the comment or spam the comment, if the admin does not enable the vendors to manage the review

### Actual Behaviour

Since Dokan 7.9, this notification is not sent to the admin at all, and instead, it is sent to the vendor...with all admin url + customers email while we hide this info from the sellers, and it also show the actions link like trash it or spam it while the admin does not enable the vendor to manage the review: https://ibb.co/vmk76fR

### Environment (please complete the following information)

```shell
1. Dokan Version: [3.9]
2. Dokan Pro Version: [3.9]
3. WooCommerce Version: [8.2]
4. Browser [all]
5. Current Theme: [all]
```

**Comment by nurul-umbhiya** [comment]
@Aunshon bhai kindly add this issue to your priority list.
@rajankarmakar Can you please test this at your convenient time?

**Comment by nurul-umbhiya** [comment]
Hello @Sophie-2e 
I just checked the staging site you've provided. What I've found out is:
1. For blog Comment: WordPress site admin receives the corresponding email. Since the admin user email and site global administrator email address are different, you are receiving two emails.
<img width="1245" alt="Screenshot 2023-10-13 at 4 19 47 PM" src="https://github.com/getdokan/dokan/assets/10240343/18a31b5c-3a6e-407d-a5dd-64072c9cc03b">
2. Store Review: Working as expected, kindly check the below image as a 
<img width="1238" alt="Screenshot 2023-10-13 at 4 29 24 PM" src="https://github.com/getdokan/dokan/assets/10240343/084943ba-0427-4a09-983a-709f47df5959">
reference.

**Comment by Sophie-2e** [comment]
Hello @nurul-umbhiya Nurul, first please remove the images in your comment ASAP, don't want to have my emails publicly exposed like this

Then:
1. Does not make sense as the admin email was replaced long time ago in Wordpress> General Settings > Administration email address. So I don't understand why it is sent to the gmail address? Also I received this email for the admin address in my mailbox, but not for the gmail, so really not sure why the gmail is showing up in your screenshot.

2. Store review is working, this ticket is only about the product review.

3. Did you receive the email for the product notification on your vendor email address with all admin url links? 
I just remade a test on my "live" website and again, only the vendor received this email, but not the admin: https://ibb.co/PgQQQgw
Then I did it on the staging website, and here too only the vendor receives the email, but it is not registered in the email log for some reason.

Waiting for your news,
Regards,
Sophie

**Comment by nurul-umbhiya** [comment]
I was able to reproduce this issue, and we've taken the initiative to fix this asap. thanks for noticing this.

**Comment by Sophie-2e** [comment]
Hello @nurul-umbhiya, have the fixes been released for:
1. the notification that is not sent to the admin at all, 
2. not send the admin notification to the vendor which has all admin url links, but instead having a dedicated email template for the vendor?

And if not, when will they be?

**Comment by nurul-umbhiya** [comment]
@Sophie-2e Yes, that's what we are going to implement. Thanks for noticing this issue.

**Comment by Sophie-2e** [comment]
@nurul-umbhiya ok so yes you will work on it, but, no it has not been released yet, did I get it right?

**Comment by nurul-umbhiya** [comment]
@Sophie-2e yes, you are right. Here is the [PR link](https://github.com/getdokan/dokan/pull/2071). Since this is a Dokan Lite feature, you can view the proposed changes. Thank you.

**Comment by Sophie-2e** [comment]
Happy Friday @nurul-umbhiya glad to see this has been fixed, when will it be released? :)
