### ISSUE TITLE
The placeholder value on the "Add bookable products" page is getting broken.

### ISSUE THREAD

**Issue by Eh-Mr-SK** [getdokan/dokan#2060]
### Bug Description

On Vendor dashbord there is booking section under bookings adding a bookable product the placeholder text is not properly visible :
![image](https://github.com/getdokan/dokan/assets/91385827/0d874655-1116-4578-b8db-08cbd080406b)

### Step To Reproduce

1. Go to Vendor dashboard
2. Bookings 
3. Add bookable product

### Expected Behaviour

It should show placeholder proplery in mobile device as well 

### Actual Behaviour

Placeholder text half getting broken

### Environment (please complete the following information)

```shell
1. Dokan Version: [v3.9.1]
2. Dokan Pro Version: [v3.9.2]
3. WooCommerce Version: [v8.2.1]
4. Browser [chrome]
5. Current Theme: [BuddyBoss]
```

**Comment by YeasinArafat1998** [comment]
Can you please switch the theme you are using and give it a try?
