### ISSUE TITLE
CUSTOMER SUPPORT functionalities - If admin answers ticket, customer does not receive the email notification

### ISSUE THREAD

**Issue by Sophie-2e** [getdokan/dokan#2067]
### Bug Description

Following up this old GitHub issue: https://github.com/getdokan/dokan/issues/2013

Hello @nurul-umbhiya and @Aunshon, I am glad to see that almost all bugs of customer support functions have been fixed, congrats!

But after testing, with Dokan 3.9.1 and Pro 3.9.2. there is just one last bug when the admin replies to the ticket:

If the Admin answers the ticket, only the vendor receives an email but the customer does not receive an email about the admin' reply.on 

### Step To Reproduce

Reply to a support ticket as an admin, vendor will receive an email notification but not the customer.
the 

### Expected Behaviour

that customer receives an email notification when the admin answers the ticket 

### Actual Behaviour

Reply to a support ticket as an admin, the vendor receives an email notification but not the customer.

### Environment (please complete the following information)

```shell
1. Dokan Version: [v3.9.1]
2. Dokan Pro Version: [v3.9.2]
3. WooCommerce Version: [v8.2.1]
4. Browser [all]
5. Current Theme: [all]
```

**Comment by Aunshon** [comment]
@rajankarmakar 

Could you please check and ensure that this issue exists. I can not find it in my setup.

**Comment by shashwatahalder01** [comment]
@Aunshon Email notification seems functioning properly. You can watch a detailed video explanation at this [link]
(https://www.loom.com/share/a9b47a4db6374a58b47e9b7c453a1c36?sid=383a51f0-1980-4d4a-ac9b-db2d1659e688)

**Comment by Sophie-2e** [comment]
Hello @Aunshon and @shashwatahalder01 , for some reason in the support ticket, I see the email address of the customer instead of his/her name. I retested again with Store Front theme and all plugins deactivated excl. woo and dokan but then 0 emails were sent (nothing to admin, nothing to customer and nothing to vendor): https://share.vidyard.com/watch/xmhj51dk5P446vvKcE2CzT?

**Comment by Aunshon** [comment]
Thank you, @Sophie-2e , for your time and patience. 

I've noticed some differences between my local setup and the email notifications you're experiencing. Specifically, I've identified an issue with new support ticket email notifications, as opposed to reply notifications, which seem to be working as expected.

To address this, I believe it's important for us to investigate your site and understand what might be happening. Could you please create a support ticket and provide us with the necessary credentials? I've also included a video link demonstrating how things are functioning on my end. Your cooperation is greatly appreciated. And also check store support email notifications are enabled on woocommerce email  settings as 

![Image](https://github.com/getdokan/dokan/assets/32583103/72077975-bf1e-4405-9f0c-698220f95aae)


https://www.awesomescreenshot.com/video/22349901?key=6e78fb2b31e68e5faca67f1a5f102211

**Comment by Sophie-2e** [comment]
Hello @Aunshon I reviewed your video but did not see the difference your are talking about, what is it? I have opened the ticket [#28304]. Waiting for your news then, thanks
