### ISSUE TITLE
When a customer buys digital and physical products from different vendors, shipping charges are applied separately to each vendor.

### ISSUE THREAD

**Issue by Fayeakuzzamantonmoy** [getdokan/dokan#2068]
### Bug Description

Customer can purchase digitial product and physical product in one cart. When a customer buys digital and physical products from different vendors, shipping charges are applied separately to each vendor.

### Step To Reproduce

1. Login as a user
2. Add one physical product from one vendor and one digital prodcut from other vendor in the cart
3. Please navigate to check out page
4. Please note that you find shipping charge separately for two different vendors.

### Expected Behaviour

Apply the shipping charge only to the vendor from whom I buy the physical product.

### Actual Behaviour

Shipping charge showing separately for two vendors.

### Environment (please complete the following information)

```shell
1. Dokan Version: v.3.9.1
2. WooCommerce Version:v.8.2.1
4. Browser: chrome
5. Current Theme: Store Front
```

**Comment by nurul-umbhiya** [comment]
@shohag121 1 hour is added only for analysis. Kindly check the issue and write a report/discuss with the analysis team if this is legit.

**Comment by shohag121** [comment]
Hi @Fayeakuzzamantonmoy,

The issue you have reported is invalid. Please check the below screenshot.

![Image](https://github.com/getdokan/dokan/assets/5476784/663e3796-5014-4a8b-a8d6-9d336ded369c)


Please check that you have checked the `virtual` checkbox on the product exit page.

**Comment by Fayeakuzzamantonmoy** [comment]
@shohag121 Bhai, I wanted to let you know that I'm still experiencing this issue on my local platform. First, I added a digital product to my cart and noticed that no shipping charge was available. You can find a reference here: https://snipboard.io/VmDXTN.jpg. Then, I added a physical product from a different vendor and noticed that the shipping charge was now showing for both vendors. You can find a reference to this issue at https://snipboard.io/UVzqRe.jpg. Could you please recheck this issue from your end? Thank you.

**Comment by shohag121** [comment]
@Fayeakuzzamantonmoy Can you please add a screenshot of the digital product edit page?

**Comment by Fayeakuzzamantonmoy** [comment]
@shohag121 Bhai, sure. Please check it here: https://snipboard.io/fGz3mT.jpg

**Comment by shohag121** [comment]
Hi, @Fayeakuzzamantonmoy Bhai,

After retrying to reproduce the mentioned issue above, it is still not reproducible.

Please do a proper conflict check of your environment and try again.





Closing this issue. Feel free to reopen the issue again if you find the explanation misleading.

Thanks.

**Comment by Fayeakuzzamantonmoy** [comment]
@shohag121 Bhai, this problem only occurs when **Dokan Pro** is deactivated on the website. Could you please recheck after disable the Dokan Pro plugin? I recheck the issue in the local platform of @YeasinArafat1998 Bhai. The issue still remain on his local platform as well.

**Comment by shohag121** [comment]
@Mohaiminulislam1989 Bhai, @imtiaz-pranto Need to discuss this issue. Currently, it is Pro only feature. Are we planning to Bring this to the lite version?

**Comment by Mohaiminulislam1989** [comment]
For this type of communications please share link to Slack and come to me for discuss InShaAllah. @shohag121 vai
