### ISSUE TITLE
Rest api (orders end point) returns wrong result

### ISSUE THREAD

**Issue by MichaelAzzer** [getdokan/dokan#2074]
### Bug Description

Rest api orders endpoint return some orders not all I have 58 order for one of vendors it returns only 3 orders
I am using jwt for auth and GET.../orders for end point

### Step To Reproduce

Test this end point with more of orders

### Expected Behaviour

return all orders for that vendor

### Actual Behaviour

Return only 3 orders from 58

### Environment (please complete the following information)

```shell
Latest release of every thing
```

**Comment by nurul-umbhiya** [comment]
This issue have been fixed on Dokan Lite Version 3.9.5
