### ISSUE TITLE
The option to publish the product directly does not function properly. 

### ISSUE THREAD

**Issue by mrgausulazam** [getdokan/dokan#2075]
### Bug Description

If an administrator activates the **Publish Products Directly** option within the WP Admin Dashboard's User Profile screen, vendors will no longer be able to publish products directly; instead, their products will be placed in the **Pending Review** mode. The issue happened in **Dokan Lite and Dokan Pro** both plugins. 

Refernece once: https://snipboard.io/56AQln.jpg
Reference two: https://snipboard.io/w5bRyu.jpg

### Step To Reproduce

1. Go to **Wp Admin Dashboard> Users> Profile** screen and enable the **Publishing** Option and save it. 
2. Go to the Vendor Dashbaord and add new products. 
3. The products status will be the **Pending Review**

### Expected Behaviour

The most optimal approach would be to publish the product directly from the vendor dashboard.

### Actual Behaviour

Products is going to the pending review instead of the published mode. 

### Environment (please complete the following information)

```shell
1. Dokan Version: [v3.9.1]
2. Dokan Pro Version: [v3.9.2]
3. WooCommerce Version: [v8.2.1]
```

**Comment by nurul-umbhiya** [comment]
@shashwatahalder01 bhai couldn't reproduce this issue on his end. 
@shohag121 kindly contact with @mrgausulazam bhai if you can't reproduce this on your end.

**Comment by shohag121** [comment]
After discussion with @mrgausulazam Bhai and @shashwatahalder01 bhai, we found the issue invalid.
