### ISSUE TITLE
Add to cart and proceed to checkout is slow when using Stripe Express

### ISSUE THREAD

**Issue by daniel-toader** [getdokan/dokan#2085]
### Bug Description

When the Stripe Express module is enabled and the vendor has a connected express account, the add to the cart step (from the product page), and the proceed to checkout step takes around 3.2 seconds each.

On my setup, when I disable Stripe Express, these speeds are around 0.4 seconds each.

This is not related to my website/theme/setup. This is an old behavior.

I tested other Dokan websites using this modern payment gateway.

The speed of both the 'add to cart' and 'proceed to checkout' functions is similarly slow on other Dokan-powered websites with Stripe Express enabled as a payment gateway.

There are no speed issues with the old Stripe Connect gateway.

It would be a worthy improvement if the developers could speed up this process.

### Expected Behaviour

Add to cart (from the product page) and proceed to checkout should be a bit faster.

### Actual Behaviour

Each step takes around 3,2 seconds.

### Environment (please complete the following information)

```shell
1. Dokan Version: [3.9.2]
2. Dokan Pro Version: [3.9.3]
3. WooCommerce Version: [8.3.0]

**Comment by nurul-umbhiya** [comment]
@daniel-toader We are working on this issue right now. Hopefully, within the next release, this issue will be fixed.

**Comment by nurul-umbhiya** [comment]
@daniel-toader this issue has been fixed, you'll get the fix on the next version of Dokan Pro.
