### ISSUE TITLE
The sub-orders remain consistently visible.

### ISSUE THREAD

**Issue by TanvirHasan19** [getdokan/dokan#2095]
### Bug Description

In the `WordPress dashboard, under WooCommerce -> Orders`, the suborders remain visible regardless of whether the 'Show sub-orders' button is clicked or not.

### Step To Reproduce

1. Go to 'WP dashboard -> WooCommerce -> Orders'
2. Check the sub-orders

### Expected Behaviour

By default, sub-orders should be collapsed. Upon clicking the 'Show sub-orders' button, the sub-orders will then become visible.

### Actual Behaviour

The suborders remain visible regardless of whether the 'Show sub-orders' button is clicked or not.

### Environment (please complete the following information)

```shell
1. Dokan Version: [e.g. v3.9.3]
3. WooCommerce Version: [e.g. v8.3.1]
```

**Comment by nurul-umbhiya** [comment]
Fixed with the latest version of Dokan Lite.
