### ISSUE TITLE
how to create a function that work immidiatly after new vendor register

### ISSUE THREAD

**Issue by zidene777** [getdokan/dokan#2099]
### Is your feature request related to a problem? Please describe.

WordPress dosn't allow  to remove the slug **/shop/** from website link

### Describe the solution you'd like
 when new vendor register a new blank page will be created with the same link of the shop username?
exp:
new vendor shop link: _**site.com/store/food**_
it create new blank page
**site.com/food**

### Describe alternatives you've considered

i'v made a theme child and i placed the code in theme function but it doesn't work correctly , it create a page everytime i reload the site after  that it work correctly by making a redirection from **site.com/food** to **site.com/shop/food**  to avoid showing up the slug **/shop/** in link when a vendor share his link in his social media platform

**Comment by sazz-pranto** [comment]
@zidene777 Thanks for creating the issue. However, we are unable to understand the scenario fully. Could you please share additional details to help us understand your request?

**Comment by sazz-pranto** [comment]
@zidene777 we're closing this issue for now as we haven't heard from you yet. Please don't hesitate to create a new issue if you find any errors or have improvement suggestions. Thanks!
