### ISSUE TITLE
Vendor announcement mails are without the announcement title

### ISSUE THREAD

**Issue by stahl111** [getdokan/dokan#2102]
### Bug Description

When a new announcement is triggered the vendors are getting an e-mail. This e-mails doesn´t contain the title of the announcement, only the content. 

Since there are announcements which are triggered automaticaly only consist of a title without announcement-content, the mail doesn´t make clear what announcement was made. (like the announcement about the vendor is not connected to stripe) 

If the mail-subject or the mail body also contains the announcement-title everything would be fine.

### Step To Reproduce

1. Go to 'Dokan; Announcements'
2. Create a new announcement for a vendor with a title 
3. Look at the mail the vendor got
4. you cant see the title in the mail 

### Expected Behaviour

The mail should contain title and content of the announcement

### Actual Behaviour

The mail only contain the content of the announcement, without the title

### Environment (please complete the following information)

```shell
1. Dokan Version: [3.9.3]
2. Dokan Pro Version: [3.9.4]
3. WooCommerce Version: [8.3.1]
```

**Comment by Sophie-2e** [comment]
Announcements do have a title. The issue you are facing is related to the Stripe Automatique Announcement only, and this GitHub issue explained the issue in detail @imtiaz-pranto: https://github.com/getdokan/dokan/issues/2179

**Comment by stahl111** [comment]
@Sophie-2e Thanks for pushing the problem. 
But i don´t think its a Stripe Automatique Announcement problem only. The samle problem occurs if you send an announcement only with title but no content. Shouldn´t be that often but it will still occure.

**Comment by Sophie-2e** [comment]
You're welcome @stahl111, glad I could help you and save you some research time :-)
