### ISSUE TITLE
Adding quick edit and edit product for every vendor

### ISSUE THREAD

**Issue by mehdimavadat** [getdokan/dokan#2103]
### Is your feature request related to a problem? Please describe.

hello to the Dokan team

can you add “quick edit” and “edit” buttons to every products of vendor role in Dokan lite?

if you more question about my request, please inform me 😎

### Describe the solution you'd like

with this feature every vendor can quick edit (opens a pop-up) and edit (link to product edit) his/her product faster and better in the frontend

**Comment by nurul-umbhiya** [comment]
Hello @mehdimavadat, I hope you’re doing well. Just wanted to let you know that we already have an Edit feature under Dokan Lite and a Quick Edit feature under Dokan Pro. If you need the quick edit feature, kindly install Dokan Pro.

**Comment by mehdimavadat** [comment]
thank you so much for informing me and adding these new features
I will come back soon with new features requests
