### ISSUE TITLE
Dokan should upgrade some basic features that are lacking quite a lot

### ISSUE THREAD

**Issue by khanhgau** [getdokan/dokan#2104]
### Is your feature request related to a problem? Please describe.

My English is not good so I will use google translate. If there are any language errors, please ignore them
1: The product does not have a price based on quantity.
For example: 1 bracelet costs $10, but if you order 5 or more, the price will be better. It will be different from wholesale and wholesale.
2: Lack of price comparison features.
For example: in any product from any supplier, it will suggest a better or perhaps cheapest price for that product.

### Describe the solution you'd like

I think if those two issues are added, perhaps this is one of the perfect applications and the best price for an e-commerce website.

**Comment by khanhgau20** [comment]
you're right

**Comment by refrigerationstore** [comment]
you're right

**Comment by imtiaz-pranto** [comment]
We have a module called the Min-Max module that allows us to set varied prices based on the quantity of a product ordered. This means that for items like tshirt, a single unit might cost $10, but if you order in larger quantities (say, 5 or more), we can set a lower price per unit. This approach is ideal for offering discounts on bulk purchases, effectively distinguishing between single-item sales and wholesale transactions.
For the second point regarding the price comparison feature, we recognize it as a valuable enhancement. We will consider adding this feature to our platform in the future. Your suggestion is appreciated, and we're always looking for ways to improve our services.

**Comment by vladimirbuild** [comment]
> We have a module called the Min-Max module that allows us to set varied prices based on the quantity of a product ordered. This means that for items like tshirt, a single unit might cost $10, but if you order in larger quantities (say, 5 or more), we can set a lower price per unit. This approach is ideal for offering discounts on bulk purchases, effectively distinguishing between single-item sales and wholesale transactions. For the second point regarding the price comparison feature, we recognize it as a valuable enhancement. We will consider adding this feature to our platform in the future. Your suggestion is appreciated, and we're always looking for ways to improve our services.

I tried the module as you said and it has the following problems, and not everyone understands how it works. Why don't you shorten it to this image, for example? I find it easier to use and more streamlined
![Screenshot_1](https://github.com/getdokan/dokan/assets/154484536/aa78c996-2c98-4619-8fdc-79d42319cee6)

**Comment by HiddlestonDavid** [comment]
> > We have a module called the Min-Max module that allows us to set varied prices based on the quantity of a product ordered. This means that for items like tshirt, a single unit might cost $10, but if you order in larger quantities (say, 5 or more), we can set a lower price per unit. This approach is ideal for offering discounts on bulk purchases, effectively distinguishing between single-item sales and wholesale transactions. For the second point regarding the price comparison feature, we recognize it as a valuable enhancement. We will consider adding this feature to our platform in the future. Your suggestion is appreciated, and we're always looking for ways to improve our services.
> 
> I tried the module as you said and it has the following problems, and not everyone understands how it works. Why don't you shorten it to this image, for example? I find it easier to use and more streamlined ![Screenshot_1](https://private-user-images.githubusercontent.com/154484536/292082209-aa78c996-2c98-4619-8fdc-79d42319cee6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMzQ0NDMsIm5iZiI6MTcwMzEzNDE0MywicGF0aCI6Ii8xNTQ0ODQ1MzYvMjkyMDgyMjA5LWFhNzhjOTk2LTJjOTgtNDYxOS04ZmRjLTc5ZDQyMzE5Y2VlNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMVQwNDQ5MDNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT01YzA2ODc2MGUzYzZkMWI5YWM4M2RlYThmYzNmNmI4NGYzYWFkN2U1NDFkMjRjMWUwYjM3NWJmZTIzMzAxYzY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.hZGbETs6-aJXhwpselG-lq8LZk4BQTQndSsN-xTbWb8)

That's right, the min-max module is so cumbersome that it doesn't even work

**Comment by imtiaz-pranto** [comment]
We understand the issue you've raised and have already taken steps to make this feature more streamlined. To address this, our team has thoroughly revised the module from scratch. To improve your experience, we've taken significant steps to enhance its user-friendliness. We rebuilt the module from the ground up, ensuring it's not only free of previous issues but also more intuitive and straightforward to use. We're thrilled to announce that this enhanced version will be available for you very soon. Keep an eye out for our upcoming releases!

**Comment by BOWWOWWOz** [comment]
> > We have a module called the Min-Max module that allows us to set varied prices based on the quantity of a product ordered. This means that for items like tshirt, a single unit might cost $10, but if you order in larger quantities (say, 5 or more), we can set a lower price per unit. This approach is ideal for offering discounts on bulk purchases, effectively distinguishing between single-item sales and wholesale transactions. For the second point regarding the price comparison feature, we recognize it as a valuable enhancement. We will consider adding this feature to our platform in the future. Your suggestion is appreciated, and we're always looking for ways to improve our services.
> 
> I tried the module as you said and it has the following problems, and not everyone understands how it works. Why don't you shorten it to this image, for example? I find it easier to use and more streamlined ![Screenshot_1](https://private-user-images.githubusercontent.com/154484536/292082209-aa78c996-2c98-4619-8fdc-79d42319cee6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMxMzYxNTIsIm5iZiI6MTcwMzEzNTg1MiwicGF0aCI6Ii8xNTQ0ODQ1MzYvMjkyMDgyMjA5LWFhNzhjOTk2LTJjOTgtNDYxOS04ZmRjLTc5ZDQyMzE5Y2VlNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjIxJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIyMVQwNTE3MzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT04MjFiYmVmODcyNGRkNjZjYTMwYzEwZTI0ZmE5NmY3NzcxZTY4MzQxM2E4MTJlYWIzZjg4NjU1NzRlYjZmNjk3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.dQLR5urv8J_jl1K0iju0L6t9QQQ22GU4rO9ZJLMUQ5A)

The min-max module is the dumbest thing I've ever used =)) 
The design does not have clear logic and is cumbersome. You are right about the problem above, the design is not optimal.

**Comment by imtiaz-pranto** [comment]
@khanhgau, I wanted to inform you that we are currently working on a revamped Min-Max module that will simplify and enhance the process. Stay tuned for future updates. Additionally, we have included price comparison as a new feature. We hope to start working on this feature in the upcoming quarters.
