### ISSUE TITLE
Products does not complete status with different vendors

### ISSUE THREAD

**Issue by mdarab** [getdokan/dokan#2106]
### Bug Description

Hello I have Dokan on my website. my digital products and my physical product have separate vendors.

When digital and physical products are ordered at the same time, only the status of physical one from the vendor becomes “completed”. The status of digital product keeps being “in process”.

What should I do?

### Expected Behaviour

The digital products should Immediately marked as "Completed" and just physical products remain as "Processing".

### Actual Behaviour

When digital and physical products are ordered at the same time, only the status of physical one from the vendor becomes “completed”. The status of digital product keeps being “in process”.

### Environment (please complete the following information)

```shell
1. Dokan Version: v3.9.4
2. Dokan Pro Version: v3.9.5
3. WooCommerce Version: v8.3.1
4. Browser chrome, safari, firefox
5. Current Theme: the7
```

**Comment by imtiaz-pranto** [comment]
@shashwatahalder01 Bhai, can you check this issue?

**Comment by shashwatahalder01** [comment]
@imtiaz-pranto Bhai, the issue seems legit.

**Comment by nurul-umbhiya** [comment]
@mdarab @shashwatahalder01 Which payment gateway you've used to purchase the order?

**Comment by shashwatahalder01** [comment]
@nurul-umbhiya bhai, I used PayPal Marketplace payment gateway

**Comment by mdarab** [comment]
@nurul-umbhiya I used Iranian payment gateway named Saman Payment gateway.

**Comment by mdarab** [comment]
Hello, is the problem solved?

**Comment by shohag121** [comment]
Hello @mdarab,

The solution was merged and will be available in the next release of the plugin.

**Comment by mdarab** [comment]
Thank you so much!
