### ISSUE TITLE
Dokan Conflicts with WooCommerce Analytics Download

### ISSUE THREAD

**Issue by eoskevin** [getdokan/dokan#2108]
### Bug Description

Hello! We are using Dokan for our online shop, but realized that it somehow conflicts with WooCommerce’s Analytics tab – with Dokan enabled, when you hit “download” on one of the Analytics reports, the email does not ever send or get generated (doesn’t even show in email logs).

We conflict-tested this with only Dokan and WooCommerce enabled and Dokan is definitely the culprit – are you guys aware of this issue already?

### Step To Reproduce

1.  Have Dokan and WC on
2.  Go to "Analytics" in left sidebar
3. Choose something like "Orders"
4. Click "Download" on the table on the right hand side
5. You get a notification that the download will be emailed, but never does when Dokan is on.

### Expected Behaviour

Orders CSV gets sent to email after clicking "Download"

### Actual Behaviour

Notification shows, but no email is sent.

### Additional Information

Only other clue is that, it seems to cause the cron job to queue multiple times but no email ever gets sent – https://share.eosw.com/GGudnl9G

### Environment (please complete the following information)

```shell
1. Dokan Version: 3.9.4
3. WooCommerce Version: 8.4.0
4. Browser Chrome
5. Current Theme: Hello
```

**Comment by fisher2470** [comment]
I tested this issue with WooCommerce 8.6 and Dokan 3.9.9 and this no longer appears to be an issue. 

Received an email at the admin email account after about 13 minutes.
