### ISSUE TITLE
QUANTITY DISCOUNT : Vendor Dashboard > Order Details - Show Empty Column no info + Double Rows Discounts Data + Coupon text

### ISSUE THREAD

**Issue by Sophie-2e** [getdokan/dokan#2109]
### Bug Description

Following up on these issues after retesting after latest updates: https://github.com/getdokan/dokan/issues/2008 
1. - [ ] there is still the empty column which is added to the Order details in the vendor dashboard. According to your support team, this column is supposed to handle the original and discounted price but the column is always empty: that there is a discount > whatever the theme: https://ibb.co/7XbJNvZ and https://ibb.co/jvKyf14 or no discount > https://ibb.co/dBZZY5H

2. - [x] there is now two rows about the Quantity Discount, displaying twice the same info Discount and Total Qiantity Discount. It is very confusing. Only the "Discount: - X euros" is interesting, the ToTal Quantity Discount is repeating the info and does not have the minus '-' sign

3. - [ ] When quantity discount used, we see the text "Coupon(s) Used Quantity Discount: X% Product Name while this is not a coupon, it is the discount quantity.

4. - [x] a bug that has been resolved in the past but which is back with the Quantity Discount field color font and alignement which differ from the other fields: https://ibb.co/99mpRFW

### Step To Reproduce

Go to 'Vendor Dashboard'
Click on 'Order > Specific Order'
Scroll down to 'Order Details'
See error: https://ibb.co/7XbJNvZ

### Expected Behaviour

1. Don't have the empty column that display 0 data
2. Don't have the "Coupon(s) Used Quantity Discount: ..." text which is related to coupon code and not quantity discount
5. Don't have the double rows about Discount + Total Quantity Discount. Don't have the Total Quantity Discount which is just redundant and do not have have the minus sign '-' 

### Actual Behaviour

https://ibb.co/7XbJNvZ

### Environment (please complete the following information)

```shell
1. Dokan Version: [3.9.5]
2. Dokan Pro Version: [3.9.6]
3. WooCommerce Version: [8.4.0]
6. Browser [all]
7. Current Theme: [Store Front, Blocksy etc...]
```

**Comment by Sophie-2e** [comment]
@imtiaz-pranto since last Dokan updates, the 2nd and 3rd points are fixed. But one issue still remain and one old fixed issue which is back...
Issues:
- [ ] still the empty column: https://ibb.co/99mpRFW 
- [ ] and a bug that has been resolved in the past but which is back with the Quantity Discount field color font and alignement which differ from the other fields: https://ibb.co/99mpRFW

**Comment by nurul-umbhiya** [comment]
@Sophie-2e Kindly create a support ticket for this issue and mention the ticket number here. We need to provide you a custom solution for this. If we remove the empty column, this will break the integration with other plugin.

**Comment by Sophie-2e** [comment]
Hello @nurul-umbhiya sorry for the late reply, here you go: #55604

**Comment by mr-gausulazam** [comment]
Hello @Sophie-2e, I have sent the necessary details to the @nurul-umbhiya bhai. I hope our concerned team starts working again to your website according to your requirements.

**Comment by Sophie-2e** [comment]
Still having this empty colums with Dokan 3.10.3: 
![Screenshot 2024-04-19 at 10 48 31](https://github.com/getdokan/dokan/assets/131655229/9aaf0324-5069-4095-9572-b5124a33a537)

What is the update? @nurul-umbhiya , @mr-gausulazam , @imtiaz-pranto ?

**Comment by Sophie-2e** [comment]
@shohag121 @mrabbani @mralaminahamed 

This issue was supposed to be fixed in the last Dokan updates according to the change log: **fix:** Removed empty columns from order details page

1. But there is still one double column https://ibb.co/YybR5zV 
2. And now the woocommerce discounts are not integrated in the tab but above with a weird coupon number: https://ibb.co/pz84jDL
3. You can see in both image that the taxes amount is not well displayed with span class and bdi: https://ibb.co/YybR5zV + https://ibb.co/pz84jDL

So it was actually better before...please check it out asap, I cannot update the live website with this.

Waiting for your news

**Comment by Sophie-2e** [comment]
@shohag121 @mrabbani @mralaminahamed @imtiaz-pranto @nurul-umbhiya 

update with Dokan 3.10.4 and Pro 3.10.3: Points 2 and 3 are resolved but there is still one double column that comes from woo, seems it is not well integrated with Dokan. I try various scenario and it seems that it can be fully hidden as it is always empty (trying to refund, edit order etc). Here is the CSS use for it: .woocommerce_order_items_wrapper.wc-order-items-editable td.wc-order-edit-line-item {display: none;}
