### ISSUE TITLE
Refund Functions with Stripe Express - Impossible to process full refunds

### ISSUE THREAD

**Issue by Sophie-2e** [getdokan/dokan#2110]
### Bug Description

Following up on this GitHub bug report after updating to the latest Dokan version: https://github.com/getdokan/dokan/issues/2009

Not possible to process full refund with Stripe Express as we cannot add a total amount that is equal to the total order amount so we cannot fully refund a customer: whatever the function we used:

- [ ]  the Coupon Store Credit
- [ ] the new Refunds functions via the Refunds tabs in the Vendor dashboard
- [x] or that we process it via the order details in the vendor dashboard. 

Images here:
- https://ibb.co/MZZtRbM
- https://ibb.co/F7TSFbT
- https://ibb.co/v1LByDv
- https://ibb.co/zmwRG6G
- https://ibb.co/pzr2M3C
- https://ibb.co/wSrmwJy

### Step To Reproduce

Testing all the refund functionalities

### Expected Behaviour

Be able to process full refund (so to process the full total order amount) via Store Credit, via the new Refunds functions via the Refunds tabs in Vendor dashboard and via the order details in the vendor dahsboard. 

### Actual Behaviour

If not full amount, it works, if refund amount equal to order amount not working:

Images here:
- https://ibb.co/MZZtRbM
- https://ibb.co/F7TSFbT
- https://ibb.co/v1LByDv
- https://ibb.co/zmwRG6G
- https://ibb.co/pzr2M3C
- https://ibb.co/wSrmwJy

### Environment (please complete the following information)

```shell
1. Dokan Version: [3.9.5]
2. Dokan Pro Version: [3.9.6]
3. WooCommerce Version: [8.4.0]
4. Browser [all]
5. Current Theme: [Blocksy / Store Front]
```

**Comment by Sophie-2e** [comment]
Udpdate: full refund process via the order details in the vendor dashboard works now but still not with the Coupon Store Credit nor with the new Refunds functions via the Refunds tabs in the Vendor dashboard

**Comment by imtiaz-pranto** [comment]
@shashwatahalder01 Bhai, can you check this issue?

**Comment by Sophie-2e** [comment]
@shashwatahalder01 @imtiaz-pranto When I say that we cannot do the full refund it is because we cannot proceed the refund of the total products amount, nor refund the full order amount as we cannot refund the shipping delivery cost with the Coupon Store Credit nor with the new Refunds functions via the Refunds tabs in the Vendor dashboard.

**Comment by Sophie-2e** [comment]
@shashwatahalder01 @imtiaz-pranto PS2: Actually still not possible to add the same amount as the product and its tax so still cannot do full refund, nor refund delivery cost with the Coupon Store Credit nor with the new Refunds functions via the Refunds tabs in the Vendor dashboard. When will this be fix?

**Comment by nurul-umbhiya** [comment]
@shohag121 since you've worked with both refund and RMA, can you please check this issue in your convenient time?

**Comment by shohag121** [comment]
@nurul-umbhiya Sure, Checking the issue.

@Mohaiminulislam1989 Bhai, @imtiaz-pranto The behavior described [above](https://github.com/getdokan/dokan/issues/2110#issuecomment-1936988072) needs further analysis and feasibility testing from your end because it is an enhancement request.

Checking the other mentioned issue where the line-item full refund is not possible.

@Sophie-2e, I'll be needing some information and settings data from your website. Is it possible to create a staging website and share it with us by creating a support ticket and mentioning this issue number on it? 


Thank You.

**Comment by Mohaiminulislam1989** [comment]
@shohag121 vai please get help from @nurul-umbhiya vai to fix this.

**Comment by shohag121** [comment]
> @shohag121 vai please get help from @nurul-umbhiya vai to fix this.

Definitely.

**Comment by Sophie-2e** [comment]
Hello @shohag121 , I am going to recreate a staging website for you because the current on is broken. Dokan support team is also working on it and it seems that someone made a change that has broken some part of the current staging website. 

I am still catching up on support ticket replies first but will open a ticket for you with a reference to this github issue as soon as I have reinstall the staging website properly ;-) Will keep you posted

**Comment by Sophie-2e** [comment]
Hello @shohag121 just to let you know that I have recreated a staging website and I asked Gausul Azam, with who I already have a ticket open about this GitHub ticket, to send you the login details of the staging website 🙂 

Please let me know if you do not receive them, and I will be looking forward to reading your findings.

**Comment by Sophie-2e** [comment]
@shohag121 apparently you cannot reproduce the issue on my website according to Gausul...don't see how you cannot reproduce it as it has never worked so here is again all proofs with all tests of all refund functionalities in video with all the bugs: https://share.vidyard.com/watch/M2KCyBe2cjzmVdJWpXYT5k?

Waiting for your news

**Comment by shohag121** [comment]
Hello @Sophie-2e,

I can see, you have the option **Round tax at subtotal level, instead of rounding per line** enabled.
It means the tax will not be round at the line item level. But when WooCommerce displays the Tax amount, it is displayed by rounding it. That is where the issue lies.

![Screenshot 2024-02-23 at 4 57 29 pm](https://github.com/getdokan/dokan/assets/5476784/e16dd637-c8ad-4f5b-9511-505a8b2b6e28)


I highly recommend you disable the option from Woocommerce tax settings.

@mr-gausulazam Please let me know if the issue persists after disabling the settings ( please create a new order to test).

**Comment by Sophie-2e** [comment]
Hello @shohag121 and @mr-gausulazam , just did the full test again without the option "Rounding" activated and I still have the exact same issue, so this is not the cause of the issue: https://share.vidyard.com/watch/6JsxdrN3hfv2UoDh3ArhCa?

Waiting for a solution,
Regards

**Comment by Sophie-2e** [comment]
@shohag121 with last dokan update lots of the bugs reported in this gthub are still there while this github has been closed: 
- Problem to fully refund an order because of taxes errors
- Problem to fully refund an order because no way of adding shipping cost
- Coupon refund: Still cannot add shipping cost to the refunded cost
