### ISSUE TITLE
DOKAN QUANTITY DISCOUNT - WPML - Discount Quantity Not Added to Translated Products

### ISSUE THREAD

**Issue by Sophie-2e** [getdokan/dokan#2122]
### Bug Description

Translated products do not have the Discount Quantity when we check the product via the Vendor dashboard:
- Original EN version with qty discount: https://ibb.co/fpDgv4c 
- Translated version with no qty discount: https://ibb.co/9TMPYrL

 And so the discount quantity is not taken into consideration on the translated cart and checkout pages:
- Original EN version CART with discount: https://ibb.co/dJVX4NB
- Translated version  CARTwith no qty discount: https://ibb.co/VLLZQv5
- Original EN version CHECKOUT with discount: https://ibb.co/6NV62R1
- Translated version  CHECKOUT with no qty discount: https://ibb.co/nLh5kdy
 
 But the products with Dokan Quantity Discount are shown in the On Sale product loop (if not a variable products) even on the translated page:
- Original EN version Product Loop on Sale: https://ibb.co/8My1nSB 
- Translated version  Product Loop on Sale: https://ibb.co/5cc1Q0t

As you can see here I have the same settings in WPML for the Woocommerce Discount Product than for the Dokan Quantity Discount product but still, the Dokan Quantity discount is not duplicated/copied to the translated product: 
- https://ibb.co/zPqFCp3

How can we make sure to copy the Dokan Discount field to the translated products automatically, and so if the seller changes it on one version, it is automatically changed on the translated version, as it is for the Woocommerce Discounted Price?

### Step To Reproduce

Add a product with dokan discount > translate product with WPML > check front end in translated version (pdt loop on sale, cart, checkout)

### Expected Behaviour

To see the same info on the translated version and if the Dokan quantity discount is modified on the original version, have the discount also modified on the translated version. Or at least to give the seller the opportunity to automatically copy this discount to the translated version of the product.

### Actual Behaviour

Discount Quantity not copied to translated product

### Environment (please complete the following information)

```shell
1. Dokan Version: [3.9.5]
2. Dokan Pro Version: [3.9.6]
3. WooCommerce Version: [8.4.0]
4. Browser [all]
5. Current Theme: [Store Front, Blocksy etc...]
```

**Comment by nurul-umbhiya** [comment]
@shohag121 Maybe enabling the sync option will fix this issue.

**Comment by shohag121** [comment]
> [@shohag121](https://github.com/shohag121) Maybe enabling the sync option will fix this issue.

Yes @nurul-umbhiya Bhai, You are right. I am adding those keys to the WPML Config file.

**Comment by Sophie-2e** [comment]
@shohag121 @nurul-umbhiya still not working after Dokan and Pro 3.10.2 update

**Comment by Sophie-2e** [comment]
where are we with this feature @shohag121 @nurul-umbhiya ?

**Comment by Sophie-2e** [comment]
@shohag121 thank you so much for fixing this issue with Dokan WPML 1.1.3 🙌 🎉👌 You rock!
