### ISSUE TITLE
How can I disable Appsero tracking. I did not consent to being tracked

### ISSUE THREAD

**Issue by gosixl** [getdokan/dokan#2134]
### Bug Description

How can I disable Appsero tracking. I did not consent to being tracked

### Step To Reproduce

How can I disable Appsero tracking. I did not consent to being tracked

### Expected Behaviour

How can I disable Appsero tracking. I did not consent to being tracked

### Actual Behaviour

How can I disable Appsero tracking. I did not consent to being tracked

### Environment (please complete the following information)

```shell
1. Dokan Version: [e.g. v3.1.2]
2. Dokan Pro Version: [e.g. v3.1.2]
3. WooCommerce Version: [e.g. v4.9.2]
4. Browser [e.g. chrome, safari]
5. Current Theme: [e.g. Store Front]
```

**Comment by imtiaz-pranto** [comment]
Find it in Dokan > Tools > Open Setup Wizard > Store Setup > Share Essentials. Turn it off to disable Appsero Tracking.
