### ISSUE TITLE
woocommerce_coupon_error causing coupon error messages not to appear on cart and checkout pages --> wp-content/plugins/dokan-pro/includes/VendorDiscount/Hooks.php

### ISSUE THREAD

**Issue by ashtonlclark** [getdokan/dokan#2135]
### Bug Description

The following file --> wp-content/plugins/dokan-pro/includes/VendorDiscount/Hooks.php has this code:

`add_action( 'woocommerce_coupon_error', [ $this, 'maybe_delete_coupon' ], 10, 3 );` on line 32. 

This specific code has stopped the coupon notifications from appearing on our cart and checkout pages. We commented the code and everything started working fine again. 

Can we resolve this properly so that we do not have to edit the plugin files each time there is a Dokan Pro update.

Thanks in advance.

### Step To Reproduce

Use an invalid coupon code on the woocommerce cart and checkout pages. No notice will be displayed.

### Expected Behaviour

A notice should be displayed when a coupon is invalid.

### Actual Behaviour

Coupon notices are not showing at all on the cart and checkout pages.

### Environment (please complete the following information)

```shell
1. Dokan Pro Version: Version 3.9.6
```

**Comment by pradeepshekhawat** [comment]
@ashtonlclark sir,

for the fix is to use the return statement (return $err) in maybe_delete_coupon function

**Update to like this**

    public function maybe_delete_coupon( $err, $err_code, $coupon ) {
        if ( Helper::is_vendor_order_discount_coupon( $coupon ) || Helper::is_vendor_product_quantity_discount_coupon( $coupon ) ) {
            $coupon->delete( true );
        }
        return $err;
    }

**Instead of this**

    public function maybe_delete_coupon( $err, $err_code, $coupon ) {
        if ( Helper::is_vendor_order_discount_coupon( $coupon ) || Helper::is_vendor_product_quantity_discount_coupon( $coupon ) ) {
            $coupon->delete( true );
        }
    }

**Comment by ashtonlclark** [comment]
Thanks @pradeepshekhawat.

Dokan team, can you fix this in the Dokan Pro plugin properly?

**Comment by Aunshon** [comment]
> Thanks @pradeepshekhawat.
> 
> Dokan team, can you fix this in the Dokan Pro plugin properly?

Thanks @ashtonlclark 
We have already given the fix and created a pull request, you will find the release soon.

**Comment by ashtonlclark** [comment]
Thank you. @Aunshon. Do you think this fix will be included in the next Dokan Pro release?
