### ISSUE TITLE
When HPOS is enabled, sub-orders disappear when orders are filtered by a specific vendor 

### ISSUE THREAD

**Issue by sazz-pranto** [getdokan/dokan#2147]
### Bug Description

As mentioned in the title.

### Step To Reproduce

1. Enable HPOS feature by navigating to the **WP admin dashboard > WooCommerce > Settings > Advanced > Features** screen as shown in this screenshot: https://snipboard.io/AU3CIG.jpg
2. Place an order consisting of products from multiple vendors
3. Go to WP admin dashboard > WooCommerce > Orders and filter orders by a vendor which is a part of the sub-order
4. Observe the filtered orders

### Expected Behaviour

When the HPOS feature is enabled, sub-orders should be displayed after orders are filtered by specific vendors

### Actual Behaviour

Please watch this screencast to have a better understanding: https://www.loom.com/share/59d06816e00d4fa28111050c044c689b?sid=61038f4c-2507-46a7-a347-1257de955038

### Additional Information

N/A

### Environment (please complete the following information)

```shell
Dokan Lite v3.9.6
WooCommerce v8.5.1
WordPress v6.4.2
```

**Comment by Mohaiminulislam1989** [comment]
@nurul-umbhiya vai please have a look on this.
