### ISSUE TITLE
Incompatibility issue with YITH Easy Login and Register Popup

### ISSUE THREAD

**Issue by AleTorrisi** [getdokan/dokan#2155]
### Bug Description

Dokan plugin prevent the registration of a new customer from the popup provided by YITH Easy Login and Register Popup.
Once you submit a request to create the profile an error message appear "An error occurred in the process", and it happen only if Dokan is enabled.

### Step To Reproduce

1. Install YITH Easy Login and Register Popup plugin
2. Add a product to the cart
3. Go to Cart page and click on "proceed to checkout page"
4. A popup will appear asking to login before proceed to checkout page, so put your email
5. System recognize the email is not in the database so a new window appear asking to set a password for the account creation
6. You'll be blocked, a message error will appear

### Expected Behaviour

You should be able create an account from the popup of YITH Easy Login and Register popup

### Actual Behaviour

Dokan is blocking the registration process, I suppose there's a code that interact with the registration process

### Environment (please complete the following information)

```shell
1. Dokan Version: 3.9.6
2. WooCommerce Version: 8.4.0
3. Current Theme: Twenty
4. YITH Easy Login and Register Popup: 1.35.0
```

**Comment by PatrickNgandu** [comment]
Experiencing the same issue with YITH Easy Login and Register Popup and Dokan enabled. Getting an "An error occurred in the process" message during the registration process. Hoping for a quick resolution from the Dokan team! 🙏

**Comment by nurul-umbhiya** [comment]
@AleTorrisi @PatrickNgandu Since YITH Easy Login and Register Popup is a premium plugin, kindly contact Dokan Support to resolve this issue.
