### ISSUE TITLE
FATAL ERROR =v3.9.9 Jan 29, 2024

### ISSUE THREAD

**Issue by nvmcrypto** [getdokan/dokan#2160]
### Bug Description

After updating to version 3.9.9, the plugin caused a fatal error in my WordPress.

29-Jan-2024 17:53:44 UTC] PHP Fatal error:  Uncaught Error: Call to undefined method Appsero\Client::updater() in /var/www/html/wp-content/plugins/dokan-pro/includes/Update.php:97
Stack trace:
#0 /var/www/html/wp-content/plugins/dokan-pro/includes/Update.php(34): WeDevs\DokanPro\Update->init_appsero()
#1 /var/www/html/wp-content/plugins/dokan-pro/dokan-pro.php(438): WeDevs\DokanPro\Update->__construct()
#2 /var/www/html/wp-includes/class-wp-hook.php(310): Dokan_Pro->init_updater('')
#3 /var/www/html/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters(NULL, Array)
#4 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#5 /var/www/html/wp-content/plugins/dokan-lite/dokan.php(307): do_action('dokan_loaded')
#6 /var/www/html/wp-includes/class-wp-hook.php(310): WeDevs_Dokan->init_plugin('')
#7 /var/www/html/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters(NULL, Array)
#8 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#9 /var/www/html/wp-content/plugins/woocommerce/includes/class-woocommerce.php(204): do_action('woocommerce_loa...')
#10 /var/www/html/wp-includes/class-wp-hook.php(310): WooCommerce->on_plugins_loaded('')
#11 /var/www/html/wp-includes/class-wp-hook.php(334): WP_Hook->apply_filters(NULL, Array)
#12 /var/www/html/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#13 /var/www/html/wp-settings.php(495): do_action('plugins_loaded')
#14 /var/www/html/wp-config.php(128): require_once('/var/www/html/w...')
#15 /var/www/html/wp-load.php(50): require_once('/var/www/html/w...')
#16 /var/www/html/wp-blog-header.php(13): require_once('/var/www/html/w...')
#17 /var/www/html/index.php(17): require('/var/www/html/w...')
#18 {main}

### Expected Behaviour

.

### Actual Behaviour

FATAL ERROR

### Environment (please complete the following information)

```shell
1. Dokan Version: v3.9.7
2. Dokan Pro Version: 3.7.24
3. WooCommerce Version: v8.1.1 
4. Browser Chrome 120.0.6099.225  64 bits
```

**Comment by nurul-umbhiya** [comment]
@nvmcrypto Kindly update to the latest version of Dokan Pro.
