### ISSUE TITLE
The geolocation VENDOR search does not work if the user doesn't close the POSITION field  with an ENTER key

### ISSUE THREAD

**Issue by pieroamanfredi** [getdokan/dokan#2165]
### Is your feature request related to a problem? Please describe.

If a try to search a vendor with geolocation search, it doesn't work: it present all vendors without filtering.
If I terminate the LOCATION with an ENTER field, it works. 

If I search a PRODUCT, all works fine, I don't need any ENTER key.

Take a look to this video https://www.loom.com/share/3368d9cfeab44bf1a9db811cc34e6285

Many users say that there is an error!

### Describe the solution you'd like

I like that geolocation would word in sìthe same way if I search a Vendor or a Product. When I digit the LOCATION filed, I don't need to terminate it with an ENTER field.

**Comment by shohag121** [comment]
Hello @pieroamanfredi,

Thank you for reporting this issue to us.
This is a User Query caching-related bug. @Aunshon has already taken care of this bug in [this PR](https://github.com/getdokan/dokan/pull/2192).
