### ISSUE TITLE
SELLER DASHBOARD - STORE SETTINGS > Enable Min/Max > Product Category field super small, text cropped

### ISSUE THREAD

**Issue by Sophie-2e** [getdokan/dokan#2169]
### Is your feature request related to a problem? Please describe.

- [x] 1. When a seller is also an admin account, the store category field is hidden in their seller accounts as you can see for 2 different admin accounts here:

https://ibb.co/JKVYkm1
https://ibb.co/xGb5ZGs

- [ ] 2. And you can see in French and Dutch, the text fields are still cropped as it is not wide enough (cf pictures below): 

https://ibb.co/CvmJqX8
https://ibb.co/D1qT2RH
https://ibb.co/g4B9Vx7

### Describe the solution you'd like

Make the field wider so the text is not cropped

### Describe alternatives you've considered

Use CSS to correct it

**Comment by aihimel** [comment]
Hello @Sophie-2e,
Could you please add a full page screenshot for the issue you are facing.
Thanks

**Comment by Sophie-2e** [comment]
Hello @aihimel Here you go: https://ibb.co/g31S9mn

**Comment by Sophie-2e** [comment]
Any news on this? The image is not available anymore...

**Comment by Sophie-2e** [comment]
1. When a seller is also an admin account, the store category field is hidden in their seller accounts as you can see for 2 different admin accounts here => SOLVED WITH LATEST DOKAN UPDATE: 

2. the text fields are still cropped as it is not wide enough, here is the custom CSS needed and added so far to make it larger:
li.select2-search.select2-search--inline, input.select2-search__field{
    width: 400px !important;
}

**Comment by Sophie-2e** [comment]
Previous CSS was causing issue in Order tab, so here is CSS code to fix this issue, I will proceed with closing this bug, and if you want to fix it at plugin level, your choice ;-) :
.dokan-form-group.show_if_min_max_active .dokan-w5.dokan-text-left span.select2.select2-container.select2-container--default {
    width: 100% !important;
}
