### ISSUE TITLE
Changelog.txt is not found in the plugin. 

### ISSUE THREAD

**Issue by YeasinArafat1998** [getdokan/dokan#2172]
**Description of the issue:**
The changelog.txt file is not accessible and results in a 404 error message when attempting to access it.

**Steps to Reproduce:**
https://www.loom.com/share/9d22dce7e2e0422c90bb2ad17c2f8db0

**Expected Behavior:**
The changelog.txt file should be present and accessible without any errors.

**Comment by nurul-umbhiya** [comment]
Fixed on current version of Dokan.
