### ISSUE TITLE
[Dokan Pro] Germanized Module uses a Deprecated Function - vendor gets an error message

### ISSUE THREAD

**Issue by stahl111** [getdokan/dokan#2176]
### Bug Description

While adding a product at the vendor dashboard some vendors gets a error-message and cant add a product. 

Dokan Pro uses a deprecated function on line 402 in this file: dokan-pro\modules\germanized\includes\Helper.php

Like you can see here (https://github.com/vendidero/woocommerce-germanized/blob/ae74321d537390f97806ad80cc695c1efa5079c3/includes/wc-gzd-legacy-functions.php#L139) the function is deprecated since the Plugin Germanized v 3.10 

it is essential by law to use a few custom fields, which are provided by the germanized plugin so it is neccessary to have this function updated. 

### Step To Reproduce

1. Enable the plugin germanized
2. Add a product as a vendor
3. add something like delivery time
4. try to save the new product
5. See error

### Expected Behaviour

product should be added

### Actual Behaviour

Error message 

### Environment (please complete the following information)

```shell
1. Dokan Version: [3.9.9]
2. Dokan Pro Version: [3.9.10]
3. WooCommerce Version: [8.6.1]
4. Germanized [3.15.6]
```

**Comment by nurul-umbhiya** [comment]
fixed with latest version of Dokan Pro
