### ISSUE TITLE
SELLER PACKS SUBSCRIPTION / STRIPE - Sould have a Dedicated Subscription Paid/Renewal Paid Email Sent to Vendor when they subscribe to a pack and when a pack automatically renewed - FUTURE FEATURE 

### ISSUE THREAD

**Issue by Sophie-2e** [getdokan/dokan#2196]
### Is your feature request related to a problem? Please describe.

For the SELLER PACKS SUBSCRIPTION -> we should have a Dedicated Subscription Paid/Renewal Paid Email Sent to Vendor when they subscribe to a pack and when a pack is automatically renewed, when using Stripe Express.

For now, they only receive an email when they subscribe and upgrade or downgrade their subscription, but it is the email template sent to vendors when their shop is enabled ( Dokan Vendor Enable email template ) so it does not make sense to receive this email as their shop is still enabled when they automatically renew or downgrade/upgrade. 

### Describe the solution you'd like

For the SELLER PACKS SUBSCRIPTION -> we should have a Dedicated Subscription Paid/Renewal Paid Email Sent to Vendors when they subscribe to a pack and when a pack is automatically renewed when using Stripe Express.
Vendors should not receive the email  Dokan Vendor Enable email template when they downgrade/upgrade or pay a subscription.

### Describe alternatives you've considered

For now, sellers can download their invoices from their dashboard and I need to keep the Dokan Vendor Enable email template enabled for vendors who successfully pass the verification process and then buy a subscription to enable their shop. But it does not make sense that they keep receiving this email every time the subscription gets renewed or upgraded/downgraded.

### Additional context

Using Stripe Express + WPML

**Comment by Sophie-2e** [comment]
Hello @mralaminahamed & @shohag121  is a dedicated email for "Dokan Subscription Paid/Renewal Paid" Email template (Sent to Vendor when they subscribe to a pack and when a pack is automatically renewed) will be released soon as this GitHub has been closed? 🤩

cc: @mr-gausulazam @Aunshon

**Comment by mralaminahamed** [comment]
@sophie-2e, in this release we fix the bug about **multiple time email sending to the vendor about seller account is activated** when they renew their subscription package.

> Hello @mralaminahamed & @shohag121 is a dedicated email for "Dokan Subscription Paid/Renewal Paid" Email template (Sent to Vendor when they subscribe to a pack and when a pack is automatically renewed) will be released soon as this GitHub has been closed? 🤩

The new feature for email template about "Dokan Subscription Paid/Renewal Paid" will be enlisted by our @getdokan/product team and after finalize the development plan we may release in the future dokan pro release.

CC: @shams-sadek1981 @mrabbani @getdokan/product

**Comment by Sophie-2e** [comment]
Hello @mrabbani, this is an awesome news! 🎉 Thank you for your reply.

Will this feature - "Dokan Subscription Paid/Renewal Paid" email template -  will be planned for 2024 or later?

**Comment by Sophie-2e** [comment]
Hello @mrabbani, any news on when "Dokan Subscription Paid/Renewal Paid" email template will it be released / will be planned for 2024 or later?
