### ISSUE TITLE
Dokan Elementor Store Social Profile Widget - X (former Twitter) icon not shown resulting in not being show on Vendor Stores

### ISSUE THREAD

**Issue by Sophie-2e** [getdokan/dokan#2208]
FOLLOWING UP AFTER LAST DOKAN UPDATE ON : https://github.com/getdokan/dokan/issues/2087 + https://github.com/getdokan/dokan/issues/2026

### Bug Description

There is just an issue with the Dokan Elementor Store Social Profile widget where it misses the X icon resulting in the social media icon not being rendered in front end on Vendor Store Page, even if vendor has added a social media profile.

### Step To Reproduce

1. Create Vendor Page with Elementor
2. Use the Dokan Elementor Store Social Profile widget and add Twitter/X => icon not shown already in Elementor builder : 
- https://ibb.co/BB5vQyv
- https://ibb.co/3Cs2GMz

3. Check page in front end for a Vendor who has added Twitter/X in Vendor dahsboard>settings>social media: 
- https://ibb.co/VLMkwLc
- https://ibb.co/3Fp4QFB

### Expected Behaviour

Like it was previously but with X icon.

### Actual Behaviour

Not shown at all:
- https://ibb.co/BB5vQyv
- https://ibb.co/3Cs2GMz
- https://ibb.co/VLMkwLc
- https://ibb.co/3Fp4QFB

### Environment (please complete the following information)

```shell
1. Dokan Version: [3.10.1]
2. Dokan Pro Version: [3.10.1]
3. WooCommerce Version: [8.7.0]
4. Browser [all]
5. Current Theme: [all]
```

**Comment by Aunshon** [comment]
Hello @Sophie-2e hope you are doing well. I have check this issue the twitter icons are coming from elimentor and as of my elementor verion `3.20.3` is working ok. Could you please update and check it again if the issue resolves. if not could you please give us the screen record.?

**Comment by Sophie-2e** [comment]
Hello @Aunshon hope you are doing well too, so I am using Elementor 3.20.3 + Elementor Pro 3.20.2 (latest versions) and the issue is still here as you can see on this screenshots:

![Screenshot 2024-03-29 at 05 49 51](https://github.com/getdokan/dokan/assets/131655229/f32d3239-178c-4cfa-b111-48b58bb03986)
![Screenshot 2024-03-29 at 05 48 43](https://github.com/getdokan/dokan/assets/131655229/65b3ae5b-8c80-42d1-a931-28c0c28b1822)
![Screenshot 2024-03-29 at 05 48 10](https://github.com/getdokan/dokan/assets/131655229/857cbe0f-1ea0-45bf-a4b8-a0baf2ac3712)

**Comment by Aunshon** [comment]
@Sophie-2e i have re checked and i found that it is working on my end properly. Please watch my [screen record](https://jam.dev/c/572d74fc-e101-400f-b3c3-14771f540b17) and and let me know. I think you also give me a screen record and give me the site access i can debug on your site.

**Comment by Sophie-2e** [comment]
Hello @Aunshon indeed it is working also on my side now, even the thread icon reappeared, so not sure which plugin or theme caused the issue then but seems resolved now so I will go ahead with closing this GitHub :) Thanks for checking it out.
