### ISSUE TITLE
SIGN UP SELLER - RESIGN UP PENDING VERIF - ALL LANGUAGES - Notice No space between 'Didn't get the email?' and "Send again"

### ISSUE THREAD

**Issue by Sophie-2e** [getdokan/dokan#2225]
### Bug Description

Following up on customer support ticket #55586

On the SIGN UP SELLER form, when vendor SIGN UP AGAIN PENDING EMAIL VERIF - IN ALL LANGUAGES - Notice No space between 'Didn'get the email?' and Send again button.

Please review these images:
https://ibb.co/YyHPkZ6
https://ibb.co/LpyjJxg

The error notice is composed of 3 text strings where the 2nd and 3rd strings do not not have space between them.

### Step To Reproduce

On the SIGN UP SELLER form, when vendor SIGN UP AGAIN PENDING EMAIL VERIF - IN ALL LANGUAGES - Notice email pending verification

### Expected Behaviour

Have a space

### Actual Behaviour

No space

### Environment (please complete the following information)

```shell
1. Dokan Version: [with all versions included latest]
2. Dokan Pro Version: [with all versions included latest]
3. WooCommerce Version: [with all versions included latest]
4. Browser [all]
5. Current Theme: [all]
```

**Comment by mrabbani** [comment]
Hello @Sophie-2e, we weren't able to replicate this issue. Everything appears fine on our end. 

<img width="1058" alt="Screen Shot 2024-04-16 at 10 09 11 AM" src="https://github.com/getdokan/dokan/assets/4253979/3234e25f-3419-434e-985e-fc85aa89baf5">

**Is the issue still persisting on your site?**

**Comment by Sophie-2e** [comment]
Hello @mrabbani you have tested the default login/sign up page which I don't use so I don't know in this case. 

I reproduce the bugs constantly even with latest dokan version for a page where the [dokan-vendor-registration] shortcode is used to display the sign up form. Please try again with the [dokan-vendor-registration] shortcode and let me know if you cannot reproduce the bug.

**Comment by Sophie-2e** [comment]
@mrabbani Dokan 3.10.4 > Issue still here on pages where the [dokan-vendor-registration] shortcode is used to display the sign up form :

<img width="615" alt="Screenshot 2024-04-29 at 18 30 02" src="https://github.com/getdokan/dokan/assets/131655229/01cf1b37-9988-4777-9def-7601e685633d">

Any update?

**Comment by Sophie-2e** [comment]
@mrabbani with Dokan 3.11.0 on issue still there for the pages where the [dokan-vendor-registration] shortcode is used to display the sign up form

**Comment by mrabbani** [comment]
@Sophie-2e , We could not reproduce this issue locally. Pls let us know if you customised the default template.

**Comment by Sophie-2e** [comment]
Hello @mrabbani , no I did not do any customization on the default dokan notice message of the [dokan-vendor-registration] shortcode.

Can I see the picture of your test using the [dokan-vendor-registration] shortcode to display the sign up form, that does not show the same error in the error notice? 

Because your last test was done with the default woo login/sign up page but as explained last time, you need to use the dokan shortcode [dokan-vendor-registration]. 

Review the Dokan training to see how to use this shortcode: https://www.youtube.com/watch?v=pYwR1LE2kaI

Will be waiting for the picture of your test

**Comment by Sophie-2e** [comment]
Any news @mrabbani? Give me one of your staging website and I am 100% sure that I will reproduce the bug. Also send proof of your test because I feel you again tested the default woo pages while you need to use the Dokan Sign Up Shortcode https://www.youtube.com/watch?v=pYwR1LE2kaI

**Comment by mr-gausulazam** [comment]
Hello Sophie, 

I hope you are doing well. 

We are unable to reproduce this issue to our local site in the latest version. This is the reference: https://drive.google.com/file/d/1q4NMK9mk7pIpGeijFN2LoiHuUkf_VI0g/view?usp=sharing

Please update the plugin and ensure the bug again on the marketplace.

**Comment by Sophie-2e** [comment]
Hello @mr-gausulazam, just tried again and the error notice have the space now but the new function does not work well with Elementor apparently as the form background disappeared and the form change design.

With all plugin deactivated excl woo, dokan, elementor (page builder used to create the page): 
First when we go on the form, this is how it looks like: 
![Screenshot 2024-06-24 at 09 18 03](https://github.com/getdokan/dokan/assets/131655229/f53d8944-b9f9-4b49-9e47-6e0685bca623)
But once we got the error notice, the background of the form disappeared, the design is changed, some form fields do not appeared anymore, the footer of the page disappeared too:
![Screenshot 2024-06-24 at 09 16 50](https://github.com/getdokan/dokan/assets/131655229/b6a736a9-604c-40fd-bb56-4cdf03b2752f)

Please check it out and let me know.
