### ISSUE TITLE
QUANTITY DISCOUNT - Not reported in the same way (different amounts) between the customer cart/checkout/global order, the sub order and the seller order

### ISSUE THREAD

**Issue by Sophie-2e** [getdokan/dokan#2231]
Bug also reported in Customer Support ticket #56082

### Bug Description

The Discount Amount is not reported in the same way between the customer cart/checkout/global order, the sub order and the seller order so it is very confusing as it gives 3 different numbers:

Example for the same discount:

- In customer cart + checkout + Order Confirmation + My account > Orders > global order details which is the correct amount that has been deducted in Stripe Express and that appeared in Dokan Analytics: 

![Screenshot 2024-04-10 at 11 49 40](https://github.com/getdokan/dokan/assets/131655229/52f386d8-14ed-4ca6-ba56-2572bcddf6cb)

- In Woo Emails for Sellers and Customers + customer My account > Orders > global order details > sub order details:

Email customers
![Screenshot 2024-04-10 at 11 57 30](https://github.com/getdokan/dokan/assets/131655229/404c1087-e3c5-4870-8138-1784434a7690)

Email sellers:
![Screenshot 2024-04-10 at 11 59 34](https://github.com/getdokan/dokan/assets/131655229/a77ed98c-1d87-468a-99f8-8ffe1ea9acc2)

Customer My Account:
![Screenshot 2024-04-10 at 11 51 20](https://github.com/getdokan/dokan/assets/131655229/61d4f0ee-4531-4f58-8768-0595d487b560)

- the seller dashboard > orders > order details = it seems the tax amount associated with the Quantity DIscount is calculated separetly and added in the tax line instead of being added to the Quantity Discount amount. Also he sees to different amounts :

![Screenshot 2024-04-10 at 12 02 02](https://github.com/getdokan/dokan/assets/131655229/f93e2eeb-d115-48c0-996e-dfbcc485d6e0)

And you can see here the settings in woo taxes, the tax are rounded at the line level so does not makes sense to have a different number between customer cart/checkout/global order and the customer sub order. 

![Screenshot 2024-04-10 at 12 03 21](https://github.com/getdokan/dokan/assets/131655229/2c90bd10-b047-49d9-b857-d67d2831316f)

This is confusing for customers, admin and sellers who all see different amounts to talk about the exact same discount making support / refund communications difficult.

### Step To Reproduce

Pass order with a product that has a Quantity Discount and check all pages mentioned above

### Expected Behaviour

Have the same Discount Amount in all parts of the website 

### Actual Behaviour

for now only In customer cart + checkout + Order Confirmation + My account > Orders > global order details which is the correct amount that has been deducted in Stripe Express and that appeared in Dokan Analytics BUT  In Woo Emails for Sellers and Customers + customer My account > Orders > global order details > sub order detail +  the seller dashboard > orders > order details are wrong, seems rounded is wrong as well as how it is calculated with the tax

### Environment (please complete the following information)

```shell
1. Dokan Version: [3.10.2 ]
2. Dokan Pro Version: [3.10.2 ]
3. WooCommerce Version: [8.7.0 ]
4. Browser [all]
5. Current Theme: [all]
```

**Comment by devAsadNur** [comment]
@Sophie-2e Thanks for reporting the issue. But, we are not reproducing this from our end. Could you recheck once again with the latest version of `Dokan Lite` and `Dokan Pro`, please? If you still find the issue, please provide a video. Thanks again for your cooperation.

**Comment by Sophie-2e** [comment]
Hello @devAsadNur I open this ticket while testing Dokan Lite Version: [3.10.2 ] + Dokan Pro Version: [3.10.2 ] which are the latest version as you can see in my report.

**Comment by devAsadNur** [comment]
@Sophie-2e Thanks for your quick response. Could you provide a screen record, please?

**Comment by Sophie-2e** [comment]
@devAsadNur Why? What is the other info that you don't see in this ticket with the screenshots?

**Comment by devAsadNur** [comment]
@Sophie-2e Sorry for the inconvenience. I have reproduced the scenario successfully. Actually, this is not an issue.  Here total discount from customer’s perspective is 60. On the other hand, discount from seller and admin’s perspective: is 49.59 Rest 10.41 discounted from the total tax.

Please take a look at the breakdown of this order:

**Tax rate** 21%
**Product price inclusive tax** 120
**Discount Applied** 60

When tax-iclusive price 121 then product net price  100
When tax-iclusive price 120 then product net price  100 * 120 / 121 = 99.174

So Tax on product is  120 - 99.174 = 20.826

**Discount for Net product price:**
Discount for 120 is 60
Discount for 99.174 is 60 * 99.174 /120 = 49.587

**Discount for product Tax:**
Discount for 120 is 60
Discount for 20.826 is 60 * 99.174 /120 = 10.143

[Explanation Doc](https://docs.google.com/document/d/1MAVhCT_zwPn_Dd7uQjZpS8_lo2O5o0oR1RnQWL4Z5dQ/)

**Comment by Sophie-2e** [comment]
@mr-gausulazam you cannot explain the 59.99 so there is a bug....so what now?

**Comment by devAsadNur** [comment]
@Sophie-2e Just checked by placing a test order (#34512) on your staging site with same customer, same product, same settings. We couldn't reproduced the issue. The issue might be solved already.

Please test from your end once again.  If you can reproduce, then try to test the same thing with `WooCommerce` only. Disable `Dokan` and `Dokan Pro`. Then create the same price product from admin panel and place an order by applying a same amount discount from customer's side. 

Then, let us know the outcome with order numbers. Thank you.

**Comment by Sophie-2e** [comment]
Hey guys, thanks for fixing it with Dokan 3.11.0 👌

**Comment by Sophie-2e** [comment]
@devAsadNur still see this weird 59.99 euros even with Dokan 3.11.0, so why there is one cent difference on the suborder compared to the order?
