### ISSUE TITLE
SELLER DASHBOARD - SETTINGS - STORE - Save settings > errors - /wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104

### ISSUE THREAD

**Issue by Sophie-2e** [getdokan/dokan#2242]
### Bug Description

In SELLER DASHBOARD - SETTINGS - STORE > When settings saved = error in the error log because of /wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104:

2024/04/18 08:11:55 [error] 3078#3078: *16848 FastCGI sent in stderr: "PHP message: PHP Warning: Undefined array key "monday" in /wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104; PHP message: PHP Warning: Undefined array key "tuesday" in /wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104; PHP message: PHP Warning: Undefined array key "wednesday" in /wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104; PHP message: PHP Warning: Undefined array key "thursday" in /wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104; PHP message: PHP Warning: Undefined array key "friday" in /wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104; PHP message: PHP Warning: Undefined array key "saturday" in /wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104; PHP message: PHP Warning: Undefined array key "sunday" in /wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104; PHP message: PHP Warning: Undefined array key "acf" in /public/wp-content/plugins/acf-for-dokan-pro-tibys5/includes/class-acf-for-dokan-pro.php on line 582; while reading response header from upstream, referrer: "/seller-dashboard/settings/store/"

Errors happen for each day of the week.

So errors is in this code: wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104

   line 104:         if ( ! $store_days[ $day ] ) {

in this code:

    public function save_store_times( $dokan_store_time ) {
        if ( ! isset( $_POST['_wpnonce'] ) || ! wp_verify_nonce( sanitize_key( $_POST['_wpnonce'] ), 'dokan_store_settings_nonce' ) ) {
            return;
        }

        $store_days = ! empty( $_POST['store_day'] ) ? wc_clean( wp_unslash( $_POST['store_day'] ) ) : [];
        foreach ( dokan_get_translated_days() as $day => $value ) {
            if ( ! $store_days[ $day ] ) {
                $dokan_store_time[ $day ] = [
                    'status'       => 'close',
                    'opening_time' => [],
                    'closing_time' => [],
                ];

                continue;
            }

            $opening_times = ! empty( $_POST['opening_time'][ $day ] ) ? wc_clean( wp_unslash( $_POST['opening_time'][ $day ] ) ) : [];
            $closing_times = ! empty( $_POST['closing_time'][ $day ] ) ? wc_clean( wp_unslash( $_POST['closing_time'][ $day ] ) ) : [];

Did test with default theme and 0 plugins activated excluding Dokan and Woo, but same issues. You can ask video of the tests in support ticket #55598

### Step To Reproduce

In SELLER DASHBOARD - SETTINGS - STORE > When settings saved = error in the error log because of /wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104:

2024/04/18 08:11:55 [error] 3078#3078: *16848 FastCGI sent in stderr: "PHP message: PHP Warning: Undefined array key "monday" in /wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104; PHP message: PHP Warning: Undefined array key "tuesday" in /wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104; PHP message: PHP Warning: Undefined array key "wednesday" in /wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104; PHP message: PHP Warning: Undefined array key "thursday" in /wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104; PHP message: PHP Warning: Undefined array key "friday" in /wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104; PHP message: PHP Warning: Undefined array key "saturday" in /wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104; PHP message: PHP Warning: Undefined array key "sunday" in /wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104; PHP message: PHP Warning: Undefined array key "acf" in /public/wp-content/plugins/acf-for-dokan-pro-tibys5/includes/class-acf-for-dokan-pro.php on line 582; while reading response header from upstream, referrer: "/seller-dashboard/settings/store/"

### Expected Behaviour

no error in the logs

### Actual Behaviour

In SELLER DASHBOARD - SETTINGS - STORE > When settings saved = error in the error log because of /wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104:

2024/04/18 08:11:55 [error] 3078#3078: *16848 FastCGI sent in stderr: "PHP message: PHP Warning: Undefined array key "monday" in /wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104; PHP message: PHP Warning: Undefined array key "tuesday" in /wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104; PHP message: PHP Warning: Undefined array key "wednesday" in /wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104; PHP message: PHP Warning: Undefined array key "thursday" in /wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104; PHP message: PHP Warning: Undefined array key "friday" in /wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104; PHP message: PHP Warning: Undefined array key "saturday" in /wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104; PHP message: PHP Warning: Undefined array key "sunday" in /wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104; PHP message: PHP Warning: Undefined array key "acf" in /public/wp-content/plugins/acf-for-dokan-pro-tibys5/includes/class-acf-for-dokan-pro.php on line 582; while reading response header from upstream, referrer: "/seller-dashboard/settings/store/"

### Environment (please complete the following information)

```shell
1. Dokan Version: [e.g. v3.10.3]
2. Dokan Pro Version: [e.g. v3.10.3]
3. WooCommerce Version: [8.8.2]
4. Browser [all]
5. Current Theme: [all including storefront]
```

**Comment by tanjiralmamun** [comment]
Hello @Sophie-2e, this seems like a site-specific issue, as this could not be reproduced locally. Kindly create a support ticket for further investigation.

**Comment by Sophie-2e** [comment]
@tanjiralmamun No it seems like a dokan issue as error is reproduced even with storefront, no other plugins activated than dokan and woo and even with dokan 3.10.3, again:

2024/04/19 09:40:14 [error] 3078#3078: *28138 FastCGI sent in stderr: "PHP message: PHP Warning: Undefined array key "monday" in /wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104; PHP message: PHP Warning: Undefined array key "tuesday" in /wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104; PHP message: PHP Warning: Undefined array key "wednesday" in /wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104; PHP message: PHP Warning: Undefined array key "thursday" in /wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104; PHP message: PHP Warning: Undefined array key "friday" in /wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104; PHP message: PHP Warning: Undefined array key "saturday" in /public/wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104; PHP message: PHP Warning: Undefined array key "sunday" in /wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104" while reading response header from upstream, client: 2001:1c00:1531:7200:a0a4:d961:bf77:65b5, server: , request: "POST /wp-admin/admin-ajax.php HTTP/2.0", upstream: "fastcgi://unix:/var/run/php8.2-fpm-panda.sock:", , referrer: "https://staging-panda-testwebsite.kinsta.cloud/seller-dashboard/settings/store/"

So open again here: https://github.com/getdokan/dokan/issues/2249

**Comment by tanjiralmamun** [comment]
@Sophie-2e, if an issue cannot be reproduced locally, we cannot count it as a plugin-level issue. As this happening only on your site, we will address this through the ticket.

**Comment by Sophie-2e** [comment]
@tanjiralmamun Ok I am going to look for a replacement as too many issue with Dokan since 2 years. So not a viable solution, thanks for confirming once more.
