### ISSUE TITLE
SELLER DASHBOARD - SETTINGS - STORE > Impossible to edit the location name "default" of the default address once the address has been verified

### ISSUE THREAD

**Issue by Sophie-2e** [getdokan/dokan#2243]
### Bug Description

Following up on Dokan support ticket #55598, Tanvir has escalated it too and asked me to open it here:

SELLER DASHBOARD - SETTINGS - STORE > Impossible to edit the location name "default" of the default address once the address has been verified

For videos, request the ones in Dokan support ticket #55598

### Step To Reproduce

SELLER DASHBOARD - SETTINGS - STORE > Impossible to edit the location name "default" of the default address once the address has been verified

### Expected Behaviour

be able to change name

### Actual Behaviour

not able to change name

### Environment (please complete the following information)

```shell
1. Dokan Version: [e.g. v3.10.3]
2. Dokan Pro Version: [e.g. v3.10.3]
3. WooCommerce Version: [8.8.2]
4. Browser [all]
5. Current Theme: [all including storefront]
```

**Comment by tanjiralmamun** [comment]
Hello @Sophie-2e, the 'Location Name' field value can be changed, as seen in the screenshot: [](https://snipboard.io/YueazP.jpg). If that does not work on your site, it could be a site-specific issue. Therefore, continue in the support ticket for further investigation, and I am going to mark this as resolved.

**Comment by Sophie-2e** [comment]
Why do you close the github as it is your support team that asked me to open them as they also reproduce the error on their side??? Ask Tanvir:

![Screenshot 2024-04-19 at 11 54 33](https://github.com/getdokan/dokan/assets/131655229/4db2df22-f698-41f0-bd58-1314181d8214)

So reopened here as Tanvir as previously asked for this: https://github.com/getdokan/dokan/issues/2250

**Comment by Sophie-2e** [comment]
Following up on Dokan support ticket #55598, Tanvir has escalated it too and asked me to open it here:

![Screenshot 2024-04-19 at 11 54 33](https://github.com/getdokan/dokan/assets/131655229/4db2df22-f698-41f0-bd58-1314181d8214)

So reopened here: https://github.com/getdokan/dokan/issues/2250
