### ISSUE TITLE
⚠️⚠️⚠️ STRIPE ONBOARDING / DOKAN SELLERS ONBOARDING: Bugs and Wrong Redirections

### ISSUE THREAD

**Issue by Sophie-2e** [getdokan/dokan#2245]
### Bug Description

Reopening https://github.com/getdokan/dokan/issues/2228 going with support ticket 56303

I noticed 3 bugs with Stripe Express Onboarding and Dokan Vendor Onboarding:

- [ ]  1. Even if we complete the whole Stripe Onboarding, we still see in Dokan that we have not, and then we need to Finish the Stripe Onboarding again for it to work

- [ ]  2. On the first time, sellers finish the Stripe Onboarding, they are always redirected to their Seller Dashboard > Settings > Payment instead of being redirected to the Dokan Onboarding > Payment Setup.

- [ ]  3. If sellers did the Stripe process in another language than the default website language like French, they are redirected to the English Seller Dashboard > Settings > Payment instead of being redirected to the Dokan Onboarding > Payment Setup in the right language.

Here videos as proof that it never works properly:

French example from 7min05 to 11min20: ask video in customer support ticket #56303

English example from 9min50 to 14:15min : ask video in customer support ticket #56303

Other english example from 9min40 to 13min40: ask video in customer support ticket #56303

Other english example from 10min to 15min: ask video in customer support ticket #56303

So it is a constant bug that happens and that I reported various times with always the same answer from customer support that you do not have the bug when you do the test but I constantly have it and I already did the test in the past with default theme and no plugin with same results. Also happen with dokan 3.10.3. please shoot and send video of your test if it really work on your side so I have proof, the same way you keep asking me proof. 

Could you please check it out again and let me know how to fix it because I have this bug constantly for any registration in any language I have tried.

Waiting for your news

Step To Reproduce
Stripe Express Onboarding and Dokan Vendor Onboarding:

Expected Behaviour
Even if we complete the whole Stripe Onboarding, we still see in Dokan that we have not, and then we need to Finish the Stripe Onboarding again for it to work

On the first time sellers finish the Stripe Onboarding, they are always redirected to their Seller Dashboard > Settings > Payment instead of being redirected to the Dokan Onboarding > Payment Setup.

And if sellers did the Stripe process in another language than the default website language like French, they are redirected to the English Seller Dashboard > Settings > Payment instead of being redirected to the Dokan Onboarding > Payment Setup in the right language.

Actual Behaviour
Even if we complete the whole Stripe Onboarding, we still see in Dokan that we have not, and then we need to Finish the Stripe Onboarding again for it to work

On the first time sellers finish the Stripe Onboarding, they are always redirected to their Seller Dashboard > Settings > Payment instead of being redirected to the Dokan Onboarding > Payment Setup.

And if sellers did the Stripe process in another language than the default website language like French, they are redirected to the English Seller Dashboard > Settings > Payment instead of being redirected to the Dokan Onboarding > Payment Setup in the right language.

Additional Information
No response

Environment (please complete the following information)
1. Dokan Version: [all]
2. Dokan Pro Version: [all]
3. WooCommerce Version: [all]
4. Browser [all]
5. Current Theme: [all]

### Expected Behaviour

f

### Actual Behaviour

f

### Additional Information

f

### Environment (please complete the following information)

```shell
f
```

**Comment by tanjiralmamun** [comment]
Hello @Sophie-2e, as mentioned by one of our developers in the previous issue it cannot be reproduced in the local environment. I have also found the same. Please refer to the screenshot: [](https://snipboard.io/KTRuVk.jpg). The function is working as expected. As it seems, this is a site-specific issue, we will address them through the support ticket. Since this has not been determined as a plugin-level issue, I am going to mark this as resolved.

**Comment by mralaminahamed** [comment]
@Sophie-2e , good day to you! I hope this message finds you well. I would like to inform you that **we have addressed the issue regarding the wrong redirection during the Stripe Express onboarding process when a vendor uses a language other than the default language.**

This fix will be **included in an upcoming release** of Dokan Pro. Please stay tuned for the latest update. Have a wonderful day ahead!

**Comment by Sophie-2e** [comment]
Hello @mralaminahamed , yes I replied on the other GitHub when you let me know too ;-)
