### ISSUE TITLE
Stripe Gateway Fee - When Admin Pays Fee - Admin should still see the amount in the Admin order details (should only be hidden in the Vendor order details)

### ISSUE THREAD

**Issue by Sophie-2e** [getdokan/dokan#2248]
### Is your feature request related to a problem? Please describe.

Feature request for later related to : https://github.com/getdokan/dokan/issues/1954

Since Dokan 3.10.3, When Admin Pay Stripe Gateway Fee, it is indeed well hidden in the seller dashboard> orders > order details. But it is now also hidden in the Admin > Woo > Orders > Order details while the admin should still have access to this information from the order details as the admin pays the fee, so he can see the cost. Only the seller should not see it, as indeed he does not pay it.

### Describe the solution you'd like

the admin should still have access to this information from the order details as the admin pays the fee, so he can see the cost. Only the seller should not see it, as indeed he does not pay it.

### Describe alternatives you've considered

For now, admin can still go check the Dokan Admin > Report > All logs to see this information as all gateway fee registrations with Stripe have been fixed in this report now but logically, the admin should find all info needed about the order in the order details instead of navigating in various area of the admin to find info about the order.

### Additional context

This is an enhancement request for later, not an emergency as a temporary solution is available for the admin.

**Comment by mralaminahamed** [comment]
Need discussion with @mrabbani vai

**Comment by mralaminahamed** [comment]
@Sophie-2e have a nice day. As per our discussion and the current implementation, we do not add any notes related to the Stripe gateway fee on single vendor orders. However, for multi-vendor orders involving multiple sellers, a note regarding the gateway fee is added to the main/parent order, but not to the individual child orders.

Please note that any order notes, including gateway fee notes, are visible to both vendors and admins within their respective WooCommerce dashboards. This behavior follows the default WooCommerce system for order notes visibility.

While we cannot customize the notes to only display for admins, we have implemented order meta data specifically to store the gateway fee information. Admins can access and view the gateway fee details for each order through this meta data.

If you need any further assistance with accessing the gateway fee notes or meta data, I recommend reaching out to our support team for additional guidance.

### References:
- Order Notes (Single order: 34944), [Screenshots here](https://drive.google.com/file/d/1Vr0glOmi6ioJekc0IgqjfEXLH9I3olgi/view?usp=sharing)
- Order Notes (Multivendor order, main orrder: 34665), [Screenshots here](https://drive.google.com/file/d/1VtTP2x3pzz8Y8I6xOC6QZML2LOtEiGCE/view?usp=sharing)
- Order meta data (Single order: 34944), [Screenshots here](https://drive.google.com/file/d/1VrQyDpBf80dHDkOKw-SzyDHMNJZXdVo6/view?usp=sharing)

**Comment by Sophie-2e** [comment]
Hey @mralaminahamed, hope you are well 🙂 Ok great very clear explanation and thanks for the detailed information with screenshots, then all good for this, I was indeed checking the suborder and not the main order ;-)
