### ISSUE TITLE
SELLER DASHBOARD - SETTINGS - STORE - Save settings > errors - /wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104

### ISSUE THREAD

**Issue by Sophie-2e** [getdokan/dokan#2249]
### Bug Description

Related to dokan support ticket 55598 and github https://github.com/getdokan/dokan/issues/2242

**ERROR CONSTANTLY REPRODUCED EVEN WITH STORE FRONT AND NO OTHER PLUGIN THAN DOKAN AND WOO AND EVEN WITH DOKAN 3.10.3: ask video in customer support ticket as proof 55598**

In SELLER DASHBOARD - SETTINGS - STORE > When settings saved = error in the error log because of /wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104:

2024/04/19 09:40:14 [error] 3078#3078: *28138 FastCGI sent in stderr: "PHP message: PHP Warning: Undefined array key "monday" in /wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104; PHP message: PHP Warning: Undefined array key "tuesday" in /wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104; PHP message: PHP Warning: Undefined array key "wednesday" in /wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104; PHP message: PHP Warning: Undefined array key "thursday" in /wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104; PHP message: PHP Warning: Undefined array key "friday" in /wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104; PHP message: PHP Warning: Undefined array key "saturday" in /public/wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104; PHP message: PHP Warning: Undefined array key "sunday" in /wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104" while reading response header from upstream, client: 2001:1c00:1531:7200:a0a4:d961:bf77:65b5, server: , request: "POST /wp-admin/admin-ajax.php HTTP/2.0", upstream: "fastcgi://unix:/var/run/php8.2-fpm-panda.sock:", , referrer: "/seller-dashboard/settings/store/"

Errors happen for each day of the week. 

Errors is in this code: wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104

line 104: if ( ! $store_days[ $day ] ) {

in this code:public function save_store_times( $dokan_store_time ) {
    if ( ! isset( $_POST['_wpnonce'] ) || ! wp_verify_nonce( sanitize_key( $_POST['_wpnonce'] ), 'dokan_store_settings_nonce' ) ) {
        return;
    }

    $store_days = ! empty( $_POST['store_day'] ) ? wc_clean( wp_unslash( $_POST['store_day'] ) ) : [];
    foreach ( dokan_get_translated_days() as $day => $value ) {
        if ( ! $store_days[ $day ] ) {
            $dokan_store_time[ $day ] = [
                'status'       => 'close',
                'opening_time' => [],
                'closing_time' => [],
            ];

            continue;
        }

        $opening_times = ! empty( $_POST['opening_time'][ $day ] ) ? wc_clean( wp_unslash( $_POST['opening_time'][ $day ] ) ) : [];
        $closing_times = ! empty( $_POST['closing_time'][ $day ] ) ? wc_clean( wp_unslash( $_POST['closing_time'][ $day ] ) ) : [];

**Did test with default theme and 0 plugins activated excluding Dokan and Woo, but same issues. You can ask video of the tests in support ticket #55598**

### Step To Reproduce

In SELLER DASHBOARD - SETTINGS - STORE > When settings saved = error in the error log because of /wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104:

2024/04/19 09:40:14 [error] 3078#3078: *28138 FastCGI sent in stderr: "PHP message: PHP Warning: Undefined array key "monday" in /wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104; PHP message: PHP Warning: Undefined array key "tuesday" in /wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104; PHP message: PHP Warning: Undefined array key "wednesday" in /wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104; PHP message: PHP Warning: Undefined array key "thursday" in /wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104; PHP message: PHP Warning: Undefined array key "friday" in /wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104; PHP message: PHP Warning: Undefined array key "saturday" in /public/wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104; PHP message: PHP Warning: Undefined array key "sunday" in /wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104" while reading response header from upstream, client: 2001:1c00:1531:7200:a0a4:d961:bf77:65b5, server: , request: "POST /wp-admin/admin-ajax.php HTTP/2.0", upstream: "fastcgi://unix:/var/run/php8.2-fpm-panda.sock:", , referrer: "seller-dashboard/settings/store/"

### Expected Behaviour

no errors

### Actual Behaviour

2024/04/19 09:40:14 [error] 3078#3078: *28138 FastCGI sent in stderr: "PHP message: PHP Warning: Undefined array key "monday" in /wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104; PHP message: PHP Warning: Undefined array key "tuesday" in /wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104; PHP message: PHP Warning: Undefined array key "wednesday" in /wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104; PHP message: PHP Warning: Undefined array key "thursday" in /wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104; PHP message: PHP Warning: Undefined array key "friday" in /wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104; PHP message: PHP Warning: Undefined array key "saturday" in /public/wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104; PHP message: PHP Warning: Undefined array key "sunday" in /wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104" while reading response header from upstream, client: 2001:1c00:1531:7200:a0a4:d961:bf77:65b5, server: , request: "POST /wp-admin/admin-ajax.php HTTP/2.0", upstream: "fastcgi://unix:/var/run/php8.2-fpm-panda.sock:", , referrer: "/seller-dashboard/settings/store/"

### Environment (please complete the following information)

```shell
1. Dokan Version: [all included 3.10.3
2. Dokan Pro Version: all included 3.10.3
3. WooCommerce Version: all
4. Browser all
5. Current Theme: store front and all
```

**Comment by tanjiralmamun** [comment]
@Sophie-2e, if an issue cannot be reproduced locally, we cannot count it as a plugin-level issue. As this happening only on your site, we will address this through the ticket. You do not need to open an issue in the GitHub repository.

**Comment by Sophie-2e** [comment]
if I can reproduce the bug with stroefront and no other plugin than dokan and woo, it does comes from dokan, and no you probably just don't do the exact same test. So ask video in customer support ticket 55598, do same test and you will see. I can reproduce the bug constantly een with last version and here proof even with no other plugin:

2024/04/19 09:40:14 [error] 3078#3078: *28138 FastCGI sent in stderr: "PHP message: PHP Warning: Undefined array key "monday" in /wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104; PHP message: PHP Warning: Undefined array key "tuesday" in /public/wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104; PHP message: PHP Warning: Undefined array key "wednesday" in /public/wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104; PHP message: PHP Warning: Undefined array key "thursday" in /wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104; PHP message: PHP Warning: Undefined array key "friday" in /wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104; PHP message: PHP Warning: Undefined array key "saturday" in /wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104; PHP message: PHP Warning: Undefined array key "sunday" in /wp-content/plugins/dokan-pro/includes/StoreTime/Settings.php on line 104" while reading response header from upstream, client: 2001:1c00:1531:7200:a0a4:d961:bf77:65b5, server: staging-panda-testwebsite.kinsta.cloud, request: "POST /wp-admin/admin-ajax.php HTTP/2.0",  referrer: "seller-dashboard/settings/store/"

Will wait foer tanvir news then as there is clearly an issue and if asked me again to open a github i will and dont close it this time. thanks.

**Comment by Sophie-2e** [comment]
Anyways @tanjiralmamun Ok I am going to look for a replacement as too many issues with Dokan since 2 years. So not a viable solution, thanks for confirming once more.
