### ISSUE TITLE
SELLER DASHBOARD - SETTINGS - STORE > All fields from company name up to bank iban (4 fields in total) are not editable at all once vendor has been verified

### ISSUE THREAD

**Issue by Sophie-2e** [getdokan/dokan#2251]
### Bug Description

**Following up on Dokan support ticket #55598, Tanvir has escalated it too and asked me to open it here:**

![Screenshot 2024-04-19 at 11 54 33](https://github.com/getdokan/dokan/assets/131655229/4db2df22-f698-41f0-bd58-1314181d8214)

SELLER DASHBOARD - SETTINGS - STORE > All fields from company name up to bank iban (4 fields in total) are not editable at all once vendor has been verified

For videos, request the ones in Dokan support ticket #55598

### Step To Reproduce

SELLER DASHBOARD - SETTINGS - STORE > All fields from company name up to bank iban (4 fields in total) are not editable at all once vendor has been verified

### Expected Behaviour

be able to change info

### Actual Behaviour

not able to change info

### Additional Information

**Following up on Dokan support ticket #55598, Tanvir has escalated it too and asked me to open it here:**

![Screenshot 2024-04-19 at 11 54 33](https://github.com/getdokan/dokan/assets/131655229/4db2df22-f698-41f0-bd58-1314181d8214)

### Environment (please complete the following information)

```shell
1. Dokan Version: [all even 3.10.3]
2. Dokan Pro Version: [all even 3.10.3]
3. WooCommerce Version: all
4. Browser all
5. Current Theme: [all included Store Front]
```

**Comment by tanjiralmamun** [comment]
Kindly do not re-open an issue that has been closed. We have closed it after a proper investigation. Any site-specific issues will be addressed through ticket.
