### ISSUE TITLE
Remove vendor from existing products

### ISSUE THREAD

**Issue by b0ss-x** [getdokan/dokan#2252]
### Is your feature request related to a problem? Please describe.

When I set up Dokan and was testing, I set up my admin account as a vendor. Now all my old Woocommerce products got assigned to me as a vendor, and I have no way of removing the vendor flag from the products.

### Describe the solution you'd like

Ability to remove vendor from products.

### Describe alternatives you've considered

If there is a way to do this in the database as a workaround, please let me know.

**Comment by mr-gausulazam** [comment]
Hello there, 

Currently, the vendor label **removal** feature is unavailable in the Dokan plugin. When an admin creates a marketplace, vendors receive accounts to sell their products. As a vendor, you have the option to sell your products in the marketplace. 

Additionally, you can deactivate vendors from the marketplace by accessing the **WP Admin Dashboard > Dokan > Vendors** screen. This will prevent their products from being displayed in the marketplace.

If you need to remove vendor information completely, it will require customization.

Regards,
