### ISSUE TITLE
Empty message from your store

### ISSUE THREAD

**Issue by danielbreves** [getdokan/dokan#2256]
### Bug Description

I'm seeing empty messages sent to vendors

![Screenshot 2024-04-24 at 9 52 01 PM](https://github.com/getdokan/dokan/assets/2517811/dbef2bf1-e54a-4e3f-8d1f-ae7ca69388a0)

### Step To Reproduce

1. Go to a vendor page
2. Fill the vendor contact form
3. Notice the message is empty

### Expected Behaviour

The message should be included in the email

### Actual Behaviour

empty messages are being sent to vendors via email

### Additional Information

Possibly caused by https://github.com/getdokan/dokan/pull/1985

### Environment (please complete the following information)

```shell
1. Dokan Version: 3.10.3
2. WooCommerce Version: 8.8.2
3. Browser: N/A
4. Current Theme: Store Front
```

**Comment by danielbreves** [comment]
cc @shohag121

**Comment by shohag121** [comment]
Hi @danielbreves,

I could not reproduce the issue locally.
Are the email templates copied and served from the theme folder? If yes, are they updated and aligned with the plugin templates?

Thank You.

**Comment by danielbreves** [comment]
Hi @shohag121, thanks for checking. Indeed my template was out of date. However, in this case, shouldn't this trigger a breaking change and major version bump?
