### ISSUE TITLE
Integration with the Blocksy theme regarding the account registration pop-up.

### ISSUE THREAD

**Issue by J-H-Mojumder** [getdokan/dokan#2279]
### Is your feature request related to a problem? Please describe.

When a vendor registers using the `account modal` of the Blocksy theme, the user does not have the capabilities of a vendor.

### Describe the solution you'd like

In the registration class we have a hook to skip nonce, `dokan_register_nonce_check`. However, it is not present on `set_new_vendor_names` and `save_vendor_info` functions according to the Blocksy theme. They proposed to add such a hook to those functions.

**Comment by mdamkhi** [comment]
Appreciate a quick solution of the registration issue with Blocksy theme.

**Comment by sergiu-radu** [comment]
Hello @mdamkhi, with pleasure :)
Hope you will be able to merge this PR soon.

Let me know in case you will need something else from our end.

Have a good day!

**Comment by sergiu-radu** [comment]
Hello @mdamkhi, @shohag121, I see you closed this issue.
Do you guys have an approximate date when the update with this fix/improvement will be released so I could inform the client?

**Comment by J-H-Mojumder** [comment]
@sergiu-radu there is a PR as you can see in [this link](https://github.com/getdokan/dokan/pull/2301). It has already been merged and I hope this will be released soon.

**Comment by sergiu-radu** [comment]
Hi @J-H-Mojumder, great, thanks for letting me know.
