### ISSUE TITLE
Unable to Delete Connected Stripe Express Account (If the user has not completed the onboarding)

### ISSUE THREAD

**Issue by daniel-toader** [getdokan/dokan#2282]
### Bug Description

If the user has not completed the onboarding from Stripe Express, or the account is rejected, we are unable to delete it.

The actual behavior: an Express Account can only be deleted if the user completes the onboarding.

<img width="771" alt="Captură de ecran din 2024-05-24 la 21 19 45" src="https://github.com/getdokan/dokan/assets/59626702/6ead1ee1-92d3-4fd9-8557-991e6bdf8924">

### Expected Behaviour

We should have the option to delete an Express Account even if the user abandons the onboarding or if the account is rejected.

### Actual Behaviour

If the user abandons the onboarding, we are stuck forever with that account in our Stripe Dashboard, and we are unable to delete it.

**Comment by prottoy210385** [comment]
Hello @daniel-toader,

As **Dokan Stripe Express** is a premium feature, please log in and visit [https://app.dokan.co/support/create](https://app.dokan.co/support/create) to create a ticket. Our Support team will assist you with this matter upon verifying your purchase validity.

Kind regards,
