### ISSUE TITLE
Stripe Express integration error

### ISSUE THREAD

**Issue by daniel-toader** [getdokan/dokan#2302]
### Bug Description

On June 20th, I opened a support ticket on dokan.co (#67904).

Fast forward to today, I received a response from Md Fayeakuzzaman advising me to address my issue here on GitHub / Dokan.

> I recognize that you've identified an error that appears to be related to integration rather than being a site-specific issue. Additionally, I see that you have previously reported this same problem. I am deeply sorry for any inconvenience this may have caused you.
> 
> Our support team primarily handles site-specific issues, which is why this particular matter has taken longer to address. Since you've identified it as an integration-oriented issue...

The related similar issue:  https://github.com/getdokan/dokan/issues/2168

Here's the new issue I'm encountering with the Stripe Express integration: When a customer changes their card, a problem occurs.

![448701602_1279477633014952_1083772132536310086_n](https://github.com/getdokan/dokan/assets/59626702/56373850-eb5c-4f83-adfc-376d5b2bbf68)

### Step To Reproduce

I enabled test mode using a Stripe Express test account and test cards, which can be found here: https://docs.stripe.com/testing.

Steps to reproduce the integration error:
I attempted a payment with a Stripe test card that had insufficient funds, using the number 4000000000009995.

Result: "Payment failed, insufficient funds."

Without leaving the checkout page or making any changes, I then attempted to complete the order using a different Stripe test card, the well-known 4242424242424242.

On the first click on the place the order button: "We're not able to process this payment. Please try again later."

On the second click on the place the order button: "You cannot modify the customer on a PaymentIntent once it has already been set. To fulfill a payment with a different customer, cancel this PaymentIntent and create a new one."

Leaving the checkout and returning starts a new payment session, and the payment with the second test card is successful.

### Expected Behaviour

Ideally, the payment intent should update to the "new customer" or retain the "old customer" given the client is the same, and only the card changes.

**Comment by daniel-toader** [comment]
Today, I encountered a payment failure with a CVC error and a generic decline. The same error occurred when the customer tried the payment again. Since this was a live payment, I am not sure what exactly went wrong, or if he changed the card or not.

The customer left the checkout, but when he returned and tried again, he successfully completed the payment with the first card he entered.

**Comment by daniel-toader** [comment]
@mralaminahamed, this is from now:

![stripe express integration fail](https://github.com/getdokan/dokan/assets/59626702/d166a8ff-550f-4892-94a5-3c8495d279d5)

The customer managed to leave the checkout and then returned. In this way he started a new session and succeed the payment.

One question.

At least, is there a way to translate "You cannot modify the customer on a PaymentIntent once it has already been set. To fulfill a payment with a different customer, cancel this PaymentIntent and create a new one." into something that make sense to the customer: in order to make a payment, leave the checkout and come back to open a new payment session?

Thank you!

**Comment by mralaminahamed** [comment]
hello @daniel-toader. Thank you for bringing this to our attention. I've reviewed the situation, and here's what we need to understand:

The error message **comes directly from Stripe's server** when **Dokan Pro fails to update customer data (like card info) during the payment process**.

This message is sent as an exception from Stripe, which means **we can't directly translate or modify it**.

**Comment by daniel-toader** [comment]
This integration error seems to occur only when the customer places an order as a guest.

**Comment by mralaminahamed** [comment]
@daniel-toader,

Thank you for this valuable information about the guest checkout issue. To resolve this efficiently, I recommend contacting our support team directly. They can conduct specific tests on your setup and provide tailored solutions.

When reaching out, please reference issue #2302 and mention the Stripe Express integration error during guest checkouts. This will help our team assist you more effectively.

We appreciate your patience and feedback. It's crucial in helping us improve Dokan Pro for all users.

**Comment by daniel-toader** [comment]
@mralaminahamed,

I've open the support ticket on 20 June and they advised me to address my issue here on GitHub :)

I've mentioned this at the start.

**Comment by dan504301** [comment]
Steps to replicate (guest mode checkout):

**1.First, I tried a test payment with a generic decline. The payment failed.**

**2.Then, I tried and succeeded in the payment with a different valid card. The integration error occurred, but the payment succeeded.**

In the end, the payment went through, but it is worth an investigation by the developer team.

**Comment by dan504301** [comment]
This was present also in my initial test using Stripe Test Mode.

### Steps to replicate (guest mode checkout):

1.First, I tried a test payment with a generic decline. The payment failed.

2.Then, I tried the payment with a different valid card. The integration error occurred, but the payment succeeded.

In the end, the payment went through, but it is worth an investigation by the developer team.

**Comment by dan504301** [comment]
This was present also in my initial test using Stripe Test Mode.

### Steps to replicate (guest mode checkout):

1.First, I tried a test payment with a generic decline. The payment failed.

2.Then, I tried the payment with a different valid card. This new integration error occurred, but the payment succeeded.

In the end, the payment went through, but it is worth an investigation by the developer team.

**Comment by mralaminahamed** [comment]
Hello @dan504301,

Thank you for your continued feedback and for bringing this issue to our attention. I've thoroughly investigated the Stripe Express integration error you reported, focusing on the latest concerns you shared.

I've attempted to reproduce the issue following the steps you provided, but I haven't been able to replicate the problem on my end.

**Comment by dan504301** [comment]
Hello @mralaminahamed, the initial integration error was fixed, thank you.

Now we have a new one that is related with this fix (https://github.com/getdokan/dokan/issues/2330), this new integration error is only visible in the Stripe Dashboard.

Dashboard > Developers

The warning is only visible on the top right corner.

![Captură de ecran din 2024-08-12 la 08 34 30](https://github.com/user-attachments/assets/5bd9dc99-37c0-4e18-a3d6-29b5e06f883b)
