### ISSUE TITLE
Stripe Express (again) accounts disconnected when editing their profiles inside the Dokan dashboard

### ISSUE THREAD

**Issue by daniel-toader** [getdokan/dokan#2310]
Hello Team,

The other day, I made some changes to a couple of vendors, updating details about their businesses inside the Dokan dashboard (biography description field).

Today, I realized that their Stripe accounts were disconnected.

I fixed the issue by restoring the entire website.

Disconnect: The user is not connected to Stripe Express.

These accounts were created between April 2023 and May 2023.

I've also had a vendor in the past who only changed a minor detail in the address in the Dokan dashboard that made their Express account disconnect.

At that time, I didn't realize it, but now it makes sense. That account was connected in April 2023.

**Comment by daniel-toader** [comment]
These accounts were created over a year ago. From what I can see, newer connected accounts are fine and did not disconnect.

**Comment by daniel-toader** [comment]
I've also had a vendor in the past who only changed a minor detail in the address in the Dokan dashboard. At that time, I didn't realize it, but now it makes sense. That account was connected in April 2023.

**Comment by daniel-toader** [comment]
I saved the state of the website before the restore and I created a staged enviroment.

**A look inside the database could give the developer a clue of what happened.**

<img width="530" alt="Trashed express accounts" src="https://github.com/getdokan/dokan/assets/59626702/3e596e8d-0c42-4dc0-9b37-3f8efbd92199">

**Comment by daniel-toader** [comment]
As a side note, when changing the Stripe live key, the older database entries are updating with the new key just fine.

**Comment by daniel-toader** [comment]
As a side note, when changing the Stripe live key, the older database entries are updating with the new key just fine.

### I was able to trace back my actions.

I updated the descriptions of 10 accounts in the Dokan dashboard (vendor biography).

9 of those 10 accounts lost the acct_number from the _dokan_stripe_express_account_info database (as shown in the image above).

Only one account, which was disconnected and reconnected through the Dokan dashboard for testing purposes a couple of weeks earlier, did not disconnect.

Those accounts were connected between April and May 2023.

**Comment by daniel-toader** [comment]
### Ok, this wasn't hard to look at.

Here is the message for all the 9 disconnected accounts inside the Dokan dashboard.

1. I only deleted a p line inside the textarea area of vendor biography.
2. I didn't touched the country field, I'm 100% sure :).
3. Funny enough there's only one country to select, because we only accept onboarding from our country.

<img width="1102" alt="account" src="https://github.com/getdokan/dokan/assets/59626702/9d5ffe50-df1b-4b52-9409-0c955b38865a">

**Comment by daniel-toader** [comment]
@mralaminahamed, I was able to compare the database entries for a modified _dokan_stripe_express_account_info entry, before and after, opening the database using a code editor.

The only difference is highlighted in bold.

Before

**a:19:{s:10:\"account_id\";s:21:\"acct_12345Abcd\";**s:18:…..the rest of the _dokan_stripe_express_account_info entry.

After saving the vendor bio modification.

**a:19:{s:10:\"account_id\";s:0:\"\";**s:18:…..the rest remains identical.

**Comment by mralaminahamed** [comment]
@daniel-toader, 

Thank you for bringing this issue to our attention. We appreciate your feedback as it helps us improve Dokan Pro.

I'm pleased to inform you that **we have addressed the issue and submitted a fix.** The **solution is currently undergoing our standard development review and testing processes**. Once these stages are complete, the fix will be included in **a future release of Dokan Pro**.

We strive to maintain the highest quality in our releases, which is why we have a thorough review process. While I can't provide an exact release date at this time, please be assured that we're working diligently to incorporate this fix as soon as possible.

Thank you for your patience and continued support of Dokan Pro. If you have any further questions or concerns, please don't hesitate to reach out.
