### ISSUE TITLE
Front-end scripts that are causing issues with the 'Add to Cart' button

### ISSUE THREAD

**Issue by dan504301** [getdokan/dokan#2333]
### Bug Description

There was a severe incompatibility with the 'Add to Cart' button on the product page from the last Blocksy theme update.

The developers provided a fix for this Dokan compatibility issue.

Along with the fix, they also shared the following recommendation:

Dokan is loading certain customization-related scripts on the front end. These scripts were the cause of the problem and could potentially create issues with other themes as well. This practice is not ideal on their part.

Uppon inspecting the product page this seams to be the script loaded in the frontend   <script id="dokan-i18n-jed-js-extra">, this script seams to handle translations.

That's all the information I received, and I don't have anything further to add.

**Comment by devAsadNur** [comment]
It seems the issue has been fixed already. It can't be reproduced in the latest version of `Dokan`. So, I'm closing the issue.
