### ISSUE TITLE
Suborder Status Incorrectly Changes from Canceled to Completed When Admin Completes Main Order

### ISSUE THREAD

**Issue by Fayeakuzzamantonmoy** [getdokan/dokan#2341]
**Problem:**  
When a customer completes a purchase involving at least two vendors within one order, a single order is generated in the admin panel, which contains two suborders. Each vendor can view and manage their respective suborder in their vendor dashboard. 

**Issue:**  
If a vendor marks their suborder as canceled from the vendor dashboard, the suborder is correctly marked as canceled in the admin panel. However, if the admin later marks the entire order as completed, the previously canceled suborder is incorrectly marked as completed as well.

**Steps to Reproduce**
1. Place an order as a customer, selecting products from at least two different vendors.
2. Observe that one main order with suborders is generated in the admin panel.
3. Each vendor can see their respective suborder in their vendor dashboard.
4. Have one vendor mark their suborder as canceled from their dashboard.
5. Check the admin panel to confirm the suborder is marked as canceled.
6. Admin then marks the entire order as completed.
7. The previously canceled suborder is incorrectly marked as completed.

**Expected Behavior**
- Once a suborder is marked as canceled by a vendor, it should remain canceled even if the admin marks the main order as completed.

**Impact**
- This issue could lead to confusion for both vendors and customers, as it inaccurately reflects the status of a canceled suborder.

**Suggested Solution**
- Ensure that suborders marked as canceled remain in that state and are not affected by the admin marking the main order as completed.

**Environment**
- **Dokan Version:** 3.11.5
- **WooCommerce Version:** 9.1.4

**Comment by mralaminahamed** [comment]
@getdokan/product @mrabbani

Regarding the question of which statuses should be whitelisted for updating suborders when an admin updates the parent order, I propose the following whitelist:

1. **Pending Payment**: Can be updated to any status
2. **On Hold**: Can be updated to any status except Canceled and Refunded
3. **Processing**: Can be updated to Completed, Failed, Canceled, or Refunded
4. **Completed**: Can only be updated to Refunded
5. **Failed**: Can be updated to any status except Completed
6. **Canceled**: Cannot be automatically updated to any other status
7. **Refunded**: Cannot be automatically updated to any other status

This whitelist aims to prevent issues like the one reported in #2341, where a canceled suborder was incorrectly marked as completed. By treating Canceled and Refunded as final states that can't be automatically changed, we ensure that vendor-canceled orders remain canceled regardless of parent order updates.

@Mohaiminulislam1989 vai, let me know what approach we should follow

@getdokan/product

CC: @mrabbani vai

**Comment by Mohaiminulislam1989** [comment]
> @getdokan/product @mrabbani
> 
Regarding the question of **which statuses should be whitelisted for updating suborders** when an admin updates the parent order, I propose the following whitelist:
> 
> 1. **Pending Payment**: Can be updated to any status
> 2. **On Hold**: Can be updated to any status except Canceled and Refunded
> 3. **Processing**: Can be updated to Completed, Failed, Canceled, or Refunded
> 4. **Completed**: Can only be updated to Refunded
> 5. **Failed**: Can be updated to any status except Completed
> 6. **Canceled**: Cannot be automatically updated to any other status
> 7. **Refunded**: Cannot be automatically updated to any other status
> 
> This whitelist aims to prevent issues like the one reported in #2341, where a canceled suborder was incorrectly marked as completed. By treating Canceled and Refunded as final states that can't be automatically changed, we ensure that vendor-canceled orders remain canceled regardless of parent order updates.
> 
> @Mohaiminulislam1989 vai, let me know what approach we should follow
> 
> @getdokan/product
> 
> CC: @mrabbani vai

Your whitelist is correct, alhamdulillah.

**Comment by mralaminahamed** [comment]
# Implementation Plan: Update Sub-order Status in Dokan WordPress Plugin

## Objective
Update the `on_order_status_change` method in the Dokan WordPress plugin to handle sub-order status changes based on the main order status update, following the proposed whitelist.

## Steps

1. **Modify the `on_order_status_change` method**
   - Add a new private method to check if the status change is allowed
   - Implement the whitelist logic in this new method
   - Update the existing method to use the new whitelist check

2. **Create a new private method `is_status_change_allowed`**
   - Input: current status, new status
   - Output: boolean (true if change is allowed, false otherwise)
   - Implement the whitelist logic as defined in the product team's response

3. **Update the sub-order status change logic**
   - Before updating sub-order status, check if the change is allowed
   - If not allowed, skip the status update for that sub-order

4. **Add logging for skipped status updates**
   - Implement a logging mechanism to track skipped status updates
   - This will help in debugging and monitoring the new behavior


## Detailed Implementation

1. Modify the `on_order_status_change` method:

```php
public function on_order_status_change( $order_id, $old_status, $new_status, $order ) {
    // Existing code...

    // Update sub-order statuses
    $sub_orders = dokan()->order->get_child_orders( $order_id );
    if ( $sub_orders ) {
        foreach ( $sub_orders as $sub_order ) {
            if ( is_callable( [ $sub_order, 'update_status' ] ) ) {
                $current_status = $sub_order->get_status();
                if ( $this->is_status_change_allowed( $current_status, $new_status ) ) {
                    $sub_order->update_status( $new_status );
                } else {
                    $this->log_skipped_status_update( $sub_order->get_id(), $current_status, $new_status );
                }
            }
        }
    }

    // Remaining existing code...
}
```

2. Create the new `is_status_change_allowed` method:

```php
private function is_status_change_allowed( $current_status, $new_status ) {
    $whitelist = [
        'pending' => ['any'],
        'on-hold' => ['processing', 'completed', 'on-hold', 'pending', 'failed'],
        'processing' => ['completed', 'failed', 'cancelled', 'refunded', 'processing'],
        'completed' => ['refunded', 'completed'],
        'failed' => ['pending', 'on-hold', 'processing', 'failed', 'cancelled', 'refunded'],
        'cancelled' => ['cancelled'],
        'refunded' => ['refunded']
    ];

    if ( ! isset( $whitelist[$current_status] ) ) {
        return false;
    }

    return in_array( 'any', $whitelist[$current_status] ) || in_array( $new_status, $whitelist[$current_status] );
}
```

3. Implement the logging method:

```php
private function log_skipped_status_update( $order_id, $current_status, $new_status ) {
    error_log( sprintf( 'Dokan: Skipped status update for sub-order %d from %s to %s', $order_id, $current_status, $new_status ) );
}
```


@mrabbani vai, would you kindly review it and share your feedback?
