### ISSUE TITLE
Bug Found in dokan-lite/templates/orders/order-download-permission-html.php

### ISSUE THREAD

**Issue by git-rythmicode** [getdokan/dokan#2373]
### Bug Description

In the current version Sellers cannot revoke access on downloads inside orders.

### Step To Reproduce

1. Go to '....'

### Expected Behaviour

Sellers should be able to revoke access to downloads in orders.

### Actual Behaviour

Seller clicks revoke access and the download gets removed from the list. However, when you reload the page the download re-appears in the list.

### Additional Information

The key identifier for permissions is stored in the id field of the WC_Customer_Download object, which corresponds to the actual permission ID stored in the wp_woocommerce_downloadable_product_permissions table. 

Meaning... inside dokan-lite/templates/orders/order-download-permission-html.php : 
You should replace <?php echo esc_attr($download->permission_id); ?> with <?php echo esc_attr($download->id); ?> so that the Seller can revoke the download.

```
Look for the button :        <button
            rel="<?php echo esc_attr( absint( $download->product_id ) ) . ',' . esc_attr( $download->download_id ); ?>"
            class="revoke_access btn btn-danger btn-sm pull-right"
            data-order-id="<?php echo esc_attr( $download->order_id ); ?>"
            data-permission-id="<?php echo esc_attr( $download->permission_id ); ?>" <!-- here -- $download->permission_id -->
            data-nonce="<?php echo esc_attr( wp_create_nonce( 'revoke-access' ) ); ?>"
        >
            <?php esc_html_e( 'Revoke Access', 'dokan-lite' ); ?>
        </button>

It should read :        <button
            rel="<?php echo esc_attr( absint( $download->product_id ) ) . ',' . esc_attr( $download->download_id ); ?>"
            class="revoke_access btn btn-danger btn-sm pull-right"
            data-order-id="<?php echo esc_attr( $download->order_id ); ?>"
            data-permission-id="<?php echo esc_attr( $download->id ); ?>" <!-- here -- $download->id -->
            data-nonce="<?php echo esc_attr( wp_create_nonce( 'revoke-access' ) ); ?>"
        >
            <?php esc_html_e( 'Revoke Access', 'dokan-lite' ); ?>
        </button>
```

### Environment (please complete the following information)

```shell
1. Dokan Version: [e.g. v3.1.2.1]
```

**Comment by Fayeakuzzamantonmoy** [comment]
Thanks for bringing this to our attention, @git-rythmicode. Since this is a Pro feature, we already created [an issue](https://snipboard.io/KI7N35.jpg) in the GitHub repository (private) of Dokan Pro. Our development team will take further steps to bring a resolution to this issue.

With that being said, I am closing this issue. Again, we appreciate your contribution!
