### ISSUE TITLE
Admin's Commission Earned Value Incorrect

### ISSUE THREAD

**Issue by Adrian-Albanese** [getdokan/dokan#2398]
### Bug Description

The calculation of the commission value under the Admin's Dokan Dashboard "at a glance" is incorrect. I have had 3 sales so far with the commission set to 10%. 

Sale 1: 2x Free items
Sale 2: 3x $5 items = $15 total
Sale 3: 1x Free item

The dashboard shows $15 net sales and $30.69 commission earned. Not sure how my commission is larger than my net sale amount and why the payment gateway processing fee ($0.69) is shown as part of the commission too?
 
### Expected Behaviour

Expected: $15 net sale @ 10% commission = $1.50 commission earned (optional, show total minus processing fee)

### Actual Behaviour

Actual: $15 net sale @ 10% commission = $30.69 commission earned

### Environment (please complete the following information)

1. Dokan Version: v3.12.4
2. WooCommerce Version: 9.3.3
3. Browser: chrome
4. Current Theme: Blocksy

**Comment by TanvirHasan19** [comment]
Hi @Adrian-Albanese 

The issue you’re experiencing appears to be specific to your site. We recommend creating a support ticket [using this link](https://app.dokan.co/support/create). In the ticket, please include the staging site details, the vendor name, and, if possible, a video to help us understand the issue fully. Our support team will assist you promptly!

Thanks!
