### ISSUE TITLE
Vendor return requests shows 'No request found' even there are requests.

### ISSUE THREAD

**Issue by G-Nation** [getdokan/dokan#2400]
### Bug Description

On the vendor rma panel shows the message 'No request found even there are requests as you can see in the image: 

![Image](https://github.com/user-attachments/assets/e9b11220-78f5-4b04-bc6c-bccb23eb1c25)

After a bit of debugging in the dokan-pro\modules\rma\templates\rma\vendor-rma-requests.php file i found that the $requests array is an empty array and it shouldn't be. Looking deeper in this file i found that this hook: do_action( 'dokan_rma_reqeusts_before' ); doesn't exist anywhere in the code and i think that this is the problem.

### Step To Reproduce

1. Go to return requests on the vendor panel

### Expected Behaviour

See a list of return requests

### Actual Behaviour

Showing an empty list with the message: 'No request found'

### Environment (please complete the following information)

1. Dokan Version: 3.12.3
2. Dokan Pro Version: 3.11.2
3. WooCommerce Version: 9.3.3
4. Browser: Chrome
5. Current Theme: Astra 4.8.3
6. WordPress Version: 6.6.2

**Comment by prottoy210385** [comment]
Hello @G-Nation 

We’ve tried to replicate it on our end but were unable to, which suggests it may be specific to your site. To determine the cause of the issue, we’ll need to investigate your site. Unfortunately, we cannot provide this level of assistance through the public forum. Please submit a support ticket, and our team will be glad to help you after checking your purchase validity. You can create a ticket using this link- https://app.dokan.co/support/create

We appreciate your understanding.

Thank you!
