### ISSUE TITLE
Function _load_textdomain_just_in_time was called incorrectly

### ISSUE THREAD

**Issue by shahadul878** [getdokan/dokan#2449]
### Bug Description

Notice: Function _load_textdomain_just_in_time was called incorrectly. Translation loading for the dokan-lite domain was triggered too early. This is usually an indicator for some code in the plugin or theme running too early. Translations should be loaded at the init action or later. Please see [Debugging in WordPress](https://developer.wordpress.org/advanced-administration/debug/debug-wordpress/) for more information. (This message was added in version 6.7.0.) in /Volumes/DevRoot/themeforest/theme-plugin-dev/wp-includes/functions.php on line 6114

### Environment (please complete the following information)

```shell
1. Dokan Version: 3.13.1
2. WooCommerce Version: 9.4.2
3. Browser:chrome
```

**Comment by jeff-wood-readyup** [comment]
This issue is causing me problems as well, would appreciate an update that fixes this error as I have to keep my site on core 6.6.2 in order to avoid it.

https://make.wordpress.org/core/2024/10/21/i18n-improvements-6-7/

**Comment by dan504301** [comment]
+1

**Comment by mrabbani** [comment]
It is fixed in https://github.com/getdokan/dokan/pull/2448

Thanks for your co-operation.
